import { afterEach, describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { expectedTables, joinManifest, lintTables, MARKER, renderRegion, splitManifest } from "../cmd/lints.ts";
import { scratch, type Scratch } from "./scratch.ts";

let tmp: Scratch;
afterEach(() => tmp?.cleanup());

const WS_LINTS = {
  rust: { unsafe_code: "forbid", rust_2018_idioms: { level: "warn", priority: -1 } },
  clippy: { todo: "warn" },
};
const ROOT_MANIFEST = [
  "[workspace]",
  'members = ["crates/*"]',
  "",
  "[workspace.lints.rust]",
  'unsafe_code = "forbid"',
  'rust_2018_idioms = { level = "warn", priority = -1 }',
  "",
  "[workspace.lints.clippy]",
  'todo = "warn"',
  "",
].join("\n");
const PACKAGE = (name: string) => `[package]\nname = "${name}"\nversion = "0.1.0"\n`;

describe("nv lints region", () => {
  test("a roster crate gets the workspace table with unsafe_code at deny, rendered as the manifest writes it", () => {
    const region = renderRegion(expectedTables(WS_LINTS, "crates/nvs-host"));
    expect(region.startsWith(MARKER + "\n")).toBe(true);
    expect(region).toContain('[lints.rust]\nunsafe_code = "deny"\nrust_2018_idioms = { level = "warn", priority = -1 }\n');
    expect(region.endsWith('[lints.clippy]\ntodo = "warn"\n')).toBe(true);
    expect(WS_LINTS.rust.unsafe_code).toBe("forbid");
  });

  test("a table after the lint region and the comment above it are kept", () => {
    const text = PACKAGE("a") + "\n# why unsafe\n\n[lints.rust]\nunsafe_code = \"deny\"\n\n# the next table\n[features]\nx = []\n";
    const { head, region, tail } = splitManifest(text);
    expect(head).toBe(PACKAGE("a") + "\n# why unsafe\n\n");
    expect(region).toBe('[lints.rust]\nunsafe_code = "deny"\n');
    expect(tail).toBe("# the next table\n[features]\nx = []\n");
    expect(joinManifest(head, region, tail)).toBe(text);
  });

  test("an old generated marker starts the region, and CRLF comes out as LF", () => {
    const text = PACKAGE("a").replace(/\n/g, "\r\n") + "\r\n# @generated by tools/lints.py -- old\r\n# more\r\n\r\n[lints.rust]\r\nx = 1\r\n";
    const { head, region, tail } = splitManifest(text);
    expect(head).toBe(PACKAGE("a") + "\n");
    expect(region).toBe("# @generated by tools/lints.py -- old\n# more\n\n[lints.rust]\nx = 1\n");
    expect(tail).toBe("");
  });
});

describe("nv lints over a workspace", () => {
  function workspace(): Scratch {
    const s = scratch();
    s.put("Cargo.toml", ROOT_MANIFEST);
    s.put("crates/plain/Cargo.toml", PACKAGE("plain") + "\n[lints]\nworkspace = true\n");
    s.put("crates/bare/Cargo.toml", PACKAGE("bare"));
    s.put("crates/rogue/Cargo.toml", PACKAGE("rogue") + '\n[lints.rust]\nunsafe_code = "deny"\n');
    s.put("crates/nvs-host/Cargo.toml", PACKAGE("nvs-host") + '\n[lints.rust]\nunsafe_code = "allow"\n\n[features]\nx = []\n');
    return s;
  }

  test("a check names each way a crate is off the policy, and changes nothing", () => {
    tmp = workspace();
    const before = readFileSync(join(tmp.root, "crates/nvs-host/Cargo.toml"), "utf8");
    const { problems, rewritten } = lintTables(tmp.root, false);
    expect(rewritten).toEqual([]);
    const about = (rel: string) => problems.filter((p) => p.startsWith(rel));
    expect(about("crates/plain")).toEqual([]);
    expect(about("crates/bare")[0]).toContain("has no [lints] table at all");
    expect(about("crates/rogue")[0]).toContain("not on nv lints' UNSAFE_CRATES roster");
    expect(about("crates/nvs-host")[0]).toContain("has drifted");
    expect(about("crates/nvs-runtime")[0]).toContain("is not a workspace member");
    expect(readFileSync(join(tmp.root, "crates/nvs-host/Cargo.toml"), "utf8")).toBe(before);
  });

  test("a write regenerates the region, keeps the table after it, and a second check is clean for that crate", () => {
    tmp = workspace();
    const { rewritten } = lintTables(tmp.root, true);
    expect(rewritten.map((r) => r.rel)).toEqual(["crates/nvs-host"]);
    const text = readFileSync(join(tmp.root, "crates/nvs-host/Cargo.toml"), "utf8");
    expect(text).toContain('unsafe_code = "deny"');
    expect(text).not.toContain('"allow"');
    expect(text.endsWith('todo = "warn"\n\n[features]\nx = []\n')).toBe(true);
    expect(lintTables(tmp.root, false).problems.filter((p) => p.startsWith("crates/nvs-host"))).toEqual([]);
  });
});
