//! `nvs info` — one call that answers "what is this binary, and what is in
//! it?", the way `php -i` does for PHP.
//!
//! Two things are printed. The first is the build and host facts `build.rs`
//! captured. The second is Novis's obligation: every third-party component
//! compiled in, and — with `--licenses` — every license text in full. Both
//! halves are here rather than split across commands because the question
//! "may I ship this, and under what terms?" is one question.
//!
//! ## Where the licensing half comes from
//!
//! `THIRD-PARTY-LICENSES.txt` is generated by `tools/nv/cmd/gen-attribution.ts`
//! from the resolved dependency graph and embedded here with `include_str!`,
//! so the notice cannot drift from the binary it describes — they are built
//! from the same tree, in the same compile. CI regenerates and diffs it, so
//! a dependency added without its notice fails the build rather than
//! shipping unattributed.
//! `rule:packaging/the-third-party-notice-is-generated-never-written-by-hand`
//! owns the policy.
//!
//! This module slices that file at its two section headings instead of
//! re-formatting it, so there is exactly one rendering of the component
//! table and it is the one a reader can also open in the repository.

use std::process::ExitCode;

/// Novis's own terms. Shipped in the binary for the same reason the
/// third-party notices are: the MIT license Novis is offered under asks that
/// its text accompany the software, and a binary handed to someone without
/// the repository is still a copy of the software.
const NVS_LICENSE: &str = include_str!("../../../LICENSE");

/// Every third-party notice, generated by `tools/nv/cmd/gen-attribution.ts`.
const ATTRIBUTION: &str = include_str!("../../../THIRD-PARTY-LICENSES.txt");

/// The two headings this module slices `ATTRIBUTION` at.
///
/// Kept as the start of a line including the trailing space before the
/// count, so they cannot match a mention of the words inside a license
/// text. `tools/nv/cmd/gen-attribution.ts` writes both; the tests below fail if
/// either side of that agreement is changed alone.
const COMPONENTS_HEADING: &str = "\nCOMPONENTS (";
const TEXTS_HEADING: &str = "\nLICENSE TEXTS (";

/// The width the two-column fields are padded to.
const LABEL: usize = 18;

/// Prints the report and returns success.
///
/// There is nothing here that can fail: every value is either a compile-time
/// constant or a query whose failure is itself reportable as `unknown`.
pub(crate) fn run(licenses: bool) -> ExitCode {
    print!("{}", report(licenses));
    ExitCode::SUCCESS
}

/// Builds the whole report as a string.
///
/// Separate from [`run`] so the tests can assert on it without capturing
/// standard output.
fn report(licenses: bool) -> String {
    let mut out = String::new();
    let (components, texts) = sections();

    heading(&mut out, &format!("Novis {}", env!("CARGO_PKG_VERSION")));

    out.push_str("\nBuild\n");
    row(&mut out, "version", env!("CARGO_PKG_VERSION"));
    row(&mut out, "commit", env!("NVS_COMMIT"));
    row(&mut out, "commit date", env!("NVS_COMMIT_DATE"));
    row(&mut out, "profile", env!("NVS_PROFILE"));
    row(&mut out, "target", env!("NVS_TARGET"));
    row(&mut out, "built on", env!("NVS_HOST"));
    row(&mut out, "compiler", env!("NVS_RUSTC"));
    row(
        &mut out,
        "code generator",
        &format!("Cranelift {}", env!("NVS_CRANELIFT")),
    );

    out.push_str("\nHost\n");
    row(&mut out, "operating system", std::env::consts::OS);
    row(&mut out, "architecture", std::env::consts::ARCH);
    row(&mut out, "cpu parallelism", &parallelism());
    row(&mut out, "executable", &current_exe());

    out.push_str("\nLicensing\n");
    row(&mut out, "nvs", "MIT");
    row(&mut out, "third-party", "listed below");
    if licenses {
        row(&mut out, "license texts", "included below");
    } else {
        row(&mut out, "license texts", "run `nvs info --licenses`");
    }

    out.push('\n');
    out.push_str(components.trim_end());
    out.push('\n');

    if licenses {
        out.push('\n');
        heading(&mut out, "NOVIS'S OWN LICENSE");
        out.push('\n');
        out.push_str(NVS_LICENSE.trim_end());
        out.push_str("\n\n\n");
        out.push_str(texts.trim_end());
    }

    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Splits [`ATTRIBUTION`] into its component table and its license texts.
///
/// A missing heading returns the whole file as the first half rather than
/// panicking: printing too much is a cosmetic problem, and a binary that
/// aborts when asked for its licensing is a worse one. The tests below make
/// sure it never actually comes to that.
fn sections() -> (&'static str, &'static str) {
    let Some(start) = ATTRIBUTION.find(COMPONENTS_HEADING) else {
        return (ATTRIBUTION, "");
    };
    // `+ 1` skips the newline the marker starts with, which the caller has
    // already emitted as the blank line separating the sections.
    let body = &ATTRIBUTION[start + 1..];
    match body.find(TEXTS_HEADING) {
        Some(split) => (&body[..split + 1], &body[split + 1..]),
        None => (body, ""),
    }
}

fn heading(out: &mut String, title: &str) {
    out.push_str(title);
    out.push('\n');
    out.push_str(&"=".repeat(78));
    out.push('\n');
}

fn row(out: &mut String, label: &str, value: &str) {
    out.push_str(&format!("  {label:<LABEL$}  {value}\n"));
}

fn parallelism() -> String {
    std::thread::available_parallelism().map_or_else(|_| "unknown".to_owned(), |n| n.to_string())
}

fn current_exe() -> String {
    std::env::current_exe().map_or_else(|_| "unknown".to_owned(), |path| path.display().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The half of the agreement with `tools/nv/cmd/gen-attribution.ts` that lives
    /// on this side: if the generator renames a section, this fails rather
    /// than `nvs info` quietly printing the whole file as its summary.
    // covers: tools:cli/nvs-info
    #[test]
    fn the_attribution_file_has_both_section_headings() {
        assert!(
            ATTRIBUTION.contains(COMPONENTS_HEADING),
            "no COMPONENTS heading"
        );
        assert!(
            ATTRIBUTION.contains(TEXTS_HEADING),
            "no LICENSE TEXTS heading"
        );
        let (components, texts) = sections();
        assert!(components.starts_with("COMPONENTS ("));
        assert!(texts.starts_with("LICENSE TEXTS ("));
        // Nothing may be dropped between the two: the split is a cut, not a
        // filter, so `--licenses` prints every byte from the first heading
        // onwards.
        let start = ATTRIBUTION.find(COMPONENTS_HEADING).unwrap() + 1;
        assert_eq!(format!("{components}{texts}"), ATTRIBUTION[start..]);
    }

    /// The notice is only worth embedding if it actually names things. A
    /// generator bug that produced an empty table would otherwise pass
    /// every other test here.
    // covers: tools:cli/nvs-info
    #[test]
    fn the_component_table_is_populated() {
        let (components, _) = sections();
        assert!(
            components.contains("cranelift-codegen"),
            "cranelift missing"
        );
        assert!(components.contains("clap"), "clap missing");
        // One line per component plus the heading and its explanation.
        assert!(components.lines().count() > 40, "suspiciously short table");
    }

    /// Both halves of Novis's obligation reach the terminal: our own MIT text
    /// and the third-party texts, neither of which `nvs info` prints alone.
    // covers: tools:cli/nvs-info
    #[test]
    fn licenses_adds_every_text_and_the_default_omits_them() {
        let brief = report(false);
        let full = report(true);

        assert!(
            brief.contains("COMPONENTS ("),
            "the summary lost its component table"
        );
        assert!(
            !brief.contains("LICENSE TEXTS ("),
            "the summary printed the full texts"
        );
        assert!(
            brief.contains("nvs info --licenses"),
            "no pointer to the full texts"
        );

        assert!(
            full.contains("LICENSE TEXTS ("),
            "--licenses printed no texts"
        );
        assert!(
            full.contains("Permission is hereby granted"),
            "no MIT text at all"
        );
        assert!(full.contains("Apache License"), "no Apache text");
        assert!(
            full.contains("NOVIS'S OWN LICENSE"),
            "Novis's own terms are missing"
        );
        assert!(
            full.len() > brief.len() * 4,
            "--licenses barely added anything"
        );
    }

    /// `build.rs` promises never to fail the build, which means every one of
    /// these is present — as a real value or as `unknown`.
    // covers: tools:cli/nvs-info
    #[test]
    fn every_build_fact_is_reported() {
        let brief = report(false);
        for label in [
            "version",
            "commit",
            "profile",
            "target",
            "built on",
            "compiler",
            "code generator",
            "operating system",
            "architecture",
            "cpu parallelism",
            "executable",
        ] {
            assert!(brief.contains(label), "`{label}` missing from the report");
        }
        assert!(
            !env!("NVS_TARGET").is_empty(),
            "build.rs emitted an empty target"
        );
    }
}
