# The examples open UDP sockets on this computer and send messages between them.
# These lines allow that, and nothing else.
[capabilities.net]
listen = ["127.0.0.1:0"]
connect = ["127.0.0.1"]
internal = ["127.0.0.1"]
