//! The WASI a guest links: every interface of the `nvs:ext` world's WASI half that [`LINKED`]
//! names, each with an empty context (`rule:packaging/a-guest-has-no-ambient-authority`).
//!
//! The host traits are generated by `bindgen!` over `wit/nvs-ext/deps/`, the WIT the world
//! itself is written against, and implemented here. `wasi:io` is `wasmtime-wasi-io`'s, because
//! its `pollable` and stream resources are what every other interface is written in, and that
//! crate is `no_std` with no executor. `wasmtime-wasi` is not used: its host runs on `tokio`'s
//! `rt`, which `rule:concurrency/one-scheduler` refuses.
//!
//! What a guest holds, interface by interface:
//!
//! - `wasi:cli` — no environment, no arguments and no working directory. `stdin` is closed.
//!   `stdout` and `stderr` write each line to the calling request's log at `debug`, with the
//!   extension's class as the channel, through [`Budget::log`]. `exit` traps, so the call throws
//!   `ExtensionError` and the next call gets a fresh instance.
//! - `wasi:clocks` — the calling request's clocks, [`Budget::wall_clock`] and
//!   [`Budget::monotonic_clock`], so a fixed clock reaches the guest. A subscription is ready at
//!   once.
//! - `wasi:random` — the calling request's generator, [`Budget::random`], for all three
//!   interfaces, so a declared seed reaches the guest.
//! - `wasi:filesystem` — no preopened directory, so a guest never holds a descriptor. Every
//!   descriptor call answers `access`.
//!
//! `wasi:http` is in the world and not linked yet, so [`crate::load::Loader`] refuses a
//! component that imports it: a WASI import loads only when [`LINKED`] names it.
//!
//! Cost: one `ResourceTable` per instance, empty until a guest asks for a stream or a pollable,
//! and a line of at most twice [`PERMIT`] per output stream a guest asks for, all freed with the
//! instance.

use std::sync::Arc;

use wasmtime::component::{HasData, Linker, Resource, ResourceTable};
use wasmtime_wasi_io::bytes::Bytes;
use wasmtime_wasi_io::poll::{DynPollable, Pollable, subscribe};
use wasmtime_wasi_io::streams::{
    DynInputStream, DynOutputStream, InputStream, OutputStream, StreamError, StreamResult,
};
use wasmtime_wasi_io::{IoView, async_trait};

use crate::call::{Budget, Guest, Level};

/// The host traits `bindgen!` writes for the interfaces [`LINKED`] names, `wasi:io` aside.
#[allow(
    missing_docs,
    unreachable_pub,
    clippy::all,
    reason = "generated code, named by nothing outside this module"
)]
mod bindings {
    wasmtime::component::bindgen!({
    path: "../../wit/nvs-ext",
    inline: "
        package nvs:host;

        world linked {
            import wasi:cli/environment@0.2.12;
            import wasi:cli/exit@0.2.12;
            import wasi:cli/stdin@0.2.12;
            import wasi:cli/stdout@0.2.12;
            import wasi:cli/stderr@0.2.12;
            import wasi:clocks/monotonic-clock@0.2.12;
            import wasi:clocks/wall-clock@0.2.12;
            import wasi:random/random@0.2.12;
            import wasi:random/insecure@0.2.12;
            import wasi:random/insecure-seed@0.2.12;
            import wasi:filesystem/types@0.2.12;
            import wasi:filesystem/preopens@0.2.12;
        }
    ",
    world: "nvs:host/linked",
    imports: { default: trappable },
    require_store_data_send: true,
    with: {
        "wasi:io/poll": wasmtime_wasi_io::bindings::wasi::io::poll,
        "wasi:io/streams": wasmtime_wasi_io::bindings::wasi::io::streams,
        "wasi:io/error": wasmtime_wasi_io::bindings::wasi::io::error,
    },
    });
}

use self::bindings::wasi::cli::{environment, exit, stderr, stdin, stdout};
use self::bindings::wasi::clocks::{monotonic_clock, wall_clock};
use self::bindings::wasi::filesystem::{preopens, types};
use self::bindings::wasi::random::{insecure, insecure_seed, random};

/// The WASI interfaces a guest links, without their versions: what [`link`] defines, and the
/// only WASI imports [`crate::load::Loader`] admits. `tests/wasi.rs` holds this list equal to the
/// set of interfaces a component importing one alone can be instantiated with.
pub const LINKED: &[&str] = &[
    "wasi:cli/environment",
    "wasi:cli/exit",
    "wasi:cli/stdin",
    "wasi:cli/stdout",
    "wasi:cli/stderr",
    "wasi:clocks/monotonic-clock",
    "wasi:clocks/wall-clock",
    "wasi:random/random",
    "wasi:random/insecure",
    "wasi:random/insecure-seed",
    "wasi:filesystem/types",
    "wasi:filesystem/preopens",
    "wasi:io/error",
    "wasi:io/poll",
    "wasi:io/streams",
];

/// One instance's WASI state: the resources its streams and pollables live in, and the request
/// and channel its output is logged to.
pub(crate) struct Context {
    table: ResourceTable,
    budget: Arc<dyn Budget>,
    channel: Arc<str>,
}

impl Context {
    /// An empty context whose output goes to `budget`'s log under `channel`.
    pub(crate) fn new(budget: Arc<dyn Budget>, channel: &str) -> Self {
        Self {
            table: ResourceTable::new(),
            budget,
            channel: Arc::from(channel),
        }
    }

    /// The channel the instance's log records are written under: the extension's class.
    pub(crate) fn channel(&self) -> &str {
        &self.channel
    }

    /// A stream writing to the request's log.
    fn log(&mut self) -> wasmtime::Result<Resource<DynOutputStream>> {
        let stream: DynOutputStream = Box::new(Log {
            budget: Arc::clone(&self.budget),
            channel: Arc::clone(&self.channel),
            line: Vec::new(),
        });
        Ok(self.table.push(stream)?)
    }
}

impl std::fmt::Debug for Context {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Context").finish_non_exhaustive()
    }
}

impl IoView for Guest {
    fn table(&mut self) -> &mut ResourceTable {
        &mut self.wasi.table
    }
}

/// The `HasData` every generated `add_to_linker` reaches [`Context`] through.
struct Wasi;

impl HasData for Wasi {
    type Data<'a> = &'a mut Context;
}

/// Defines every interface [`LINKED`] names in `linker`.
///
/// # Errors
///
/// When an interface is already defined.
pub(crate) fn link(linker: &mut Linker<Guest>) -> wasmtime::Result<()> {
    fn cx(guest: &mut Guest) -> &mut Context {
        &mut guest.wasi
    }
    wasmtime_wasi_io::add_to_linker_async(linker)?;
    environment::add_to_linker::<Guest, Wasi>(linker, cx)?;
    exit::add_to_linker::<Guest, Wasi>(linker, cx)?;
    stdin::add_to_linker::<Guest, Wasi>(linker, cx)?;
    stdout::add_to_linker::<Guest, Wasi>(linker, cx)?;
    stderr::add_to_linker::<Guest, Wasi>(linker, cx)?;
    monotonic_clock::add_to_linker::<Guest, Wasi>(linker, cx)?;
    wall_clock::add_to_linker::<Guest, Wasi>(linker, cx)?;
    random::add_to_linker::<Guest, Wasi>(linker, cx)?;
    insecure::add_to_linker::<Guest, Wasi>(linker, cx)?;
    insecure_seed::add_to_linker::<Guest, Wasi>(linker, cx)?;
    types::add_to_linker::<Guest, Wasi>(linker, cx)?;
    preopens::add_to_linker::<Guest, Wasi>(linker, cx)?;
    Ok(())
}

impl environment::Host for Context {
    fn get_environment(&mut self) -> wasmtime::Result<Vec<(String, String)>> {
        Ok(Vec::new())
    }

    fn get_arguments(&mut self) -> wasmtime::Result<Vec<String>> {
        Ok(Vec::new())
    }

    fn initial_cwd(&mut self) -> wasmtime::Result<Option<String>> {
        Ok(None)
    }
}

impl exit::Host for Context {
    fn exit(&mut self, status: Result<(), ()>) -> wasmtime::Result<()> {
        let code = u8::from(status.is_err());
        Err(wasmtime::Error::msg(format!(
            "the guest called `exit` with status {code}"
        )))
    }

    fn exit_with_code(&mut self, code: u8) -> wasmtime::Result<()> {
        Err(wasmtime::Error::msg(format!(
            "the guest called `exit` with status {code}"
        )))
    }
}

impl stdin::Host for Context {
    fn get_stdin(&mut self) -> wasmtime::Result<Resource<DynInputStream>> {
        let stream: DynInputStream = Box::new(Closed);
        Ok(self.table.push(stream)?)
    }
}

impl stdout::Host for Context {
    fn get_stdout(&mut self) -> wasmtime::Result<Resource<DynOutputStream>> {
        self.log()
    }
}

impl stderr::Host for Context {
    fn get_stderr(&mut self) -> wasmtime::Result<Resource<DynOutputStream>> {
        self.log()
    }
}

/// `stdin`: closed, so a read returns end of stream.
struct Closed;

#[async_trait]
impl Pollable for Closed {
    async fn ready(&mut self) {}
}

impl InputStream for Closed {
    fn read(&mut self, _size: usize) -> StreamResult<Bytes> {
        Err(StreamError::Closed)
    }
}

/// `stdout` and `stderr`: each line is one record in the request's log at `debug`. A line ends
/// at `\n`, at a flush, when the stream is dropped, and when it reaches [`PERMIT`] bytes. An
/// empty line writes no record, and bytes that are not UTF-8 are replaced with `U+FFFD`.
struct Log {
    budget: Arc<dyn Budget>,
    channel: Arc<str>,
    line: Vec<u8>,
}

/// The most a guest may write to a [`Log`] at once, and the longest line it keeps before it
/// writes the line out.
const PERMIT: usize = 64 * 1024;

impl Log {
    /// Writes the line kept so far as one record, unless it is empty.
    fn emit(&mut self) {
        let line = self.line.strip_suffix(b"\r").unwrap_or(&self.line);
        if !line.is_empty() {
            let message = String::from_utf8_lossy(line);
            self.budget.log(Level::Debug, &self.channel, &message);
        }
        self.line.clear();
    }
}

impl Drop for Log {
    fn drop(&mut self) {
        self.emit();
    }
}

#[async_trait]
impl Pollable for Log {
    async fn ready(&mut self) {}
}

impl OutputStream for Log {
    fn write(&mut self, bytes: Bytes) -> StreamResult<()> {
        let mut rest = &bytes[..];
        while let Some(end) = rest.iter().position(|&byte| byte == b'\n') {
            self.line.extend_from_slice(&rest[..end]);
            self.emit();
            rest = &rest[end + 1..];
        }
        self.line.extend_from_slice(rest);
        if self.line.len() >= PERMIT {
            self.emit();
        }
        Ok(())
    }

    fn flush(&mut self) -> StreamResult<()> {
        self.emit();
        Ok(())
    }

    fn check_write(&mut self) -> StreamResult<usize> {
        Ok(PERMIT)
    }
}

/// A subscription that is ready at once.
struct Ready;

#[async_trait]
impl Pollable for Ready {
    async fn ready(&mut self) {}
}

impl monotonic_clock::Host for Context {
    fn now(&mut self) -> wasmtime::Result<u64> {
        Ok(self.budget.monotonic_clock())
    }

    fn resolution(&mut self) -> wasmtime::Result<u64> {
        Ok(1)
    }

    fn subscribe_instant(&mut self, _when: u64) -> wasmtime::Result<Resource<DynPollable>> {
        let ready = self.table.push(Ready)?;
        subscribe(&mut self.table, ready)
    }

    fn subscribe_duration(&mut self, _when: u64) -> wasmtime::Result<Resource<DynPollable>> {
        let ready = self.table.push(Ready)?;
        subscribe(&mut self.table, ready)
    }
}

impl wall_clock::Host for Context {
    fn now(&mut self) -> wasmtime::Result<wall_clock::Datetime> {
        let since = self.budget.wall_clock();
        Ok(wall_clock::Datetime {
            seconds: since.as_secs(),
            nanoseconds: since.subsec_nanos(),
        })
    }

    fn resolution(&mut self) -> wasmtime::Result<wall_clock::Datetime> {
        Ok(wall_clock::Datetime {
            seconds: 0,
            nanoseconds: 1,
        })
    }
}

impl Context {
    /// `len` bytes from the request's generator, refused past the instance's memory: a guest
    /// cannot ask the host to allocate more than a wasm32 guest could hold.
    fn bytes(&self, len: u64) -> wasmtime::Result<Vec<u8>> {
        let len = usize::try_from(len)
            .ok()
            .filter(|len| u32::try_from(*len).is_ok())
            .ok_or_else(|| {
                wasmtime::Error::msg("the guest asked for more random bytes than fit")
            })?;
        let mut out = vec![0; len];
        self.budget.random(&mut out);
        Ok(out)
    }

    /// A `u64` from the request's generator, its bytes read little-endian.
    fn u64(&self) -> u64 {
        let mut out = [0; 8];
        self.budget.random(&mut out);
        u64::from_le_bytes(out)
    }
}

impl random::Host for Context {
    fn get_random_bytes(&mut self, len: u64) -> wasmtime::Result<Vec<u8>> {
        self.bytes(len)
    }

    fn get_random_u64(&mut self) -> wasmtime::Result<u64> {
        Ok(self.u64())
    }
}

impl insecure::Host for Context {
    fn get_insecure_random_bytes(&mut self, len: u64) -> wasmtime::Result<Vec<u8>> {
        self.bytes(len)
    }

    fn get_insecure_random_u64(&mut self) -> wasmtime::Result<u64> {
        Ok(self.u64())
    }
}

impl insecure_seed::Host for Context {
    fn insecure_seed(&mut self) -> wasmtime::Result<(u64, u64)> {
        Ok((self.u64(), self.u64()))
    }
}

impl preopens::Host for Context {
    fn get_directories(&mut self) -> wasmtime::Result<Vec<(Resource<types::Descriptor>, String)>> {
        Ok(Vec::new())
    }
}

/// What every descriptor call answers: no guest holds a descriptor.
type Denied<T> = wasmtime::Result<Result<T, types::ErrorCode>>;

const fn denied<T>() -> Denied<T> {
    Ok(Err(types::ErrorCode::Access))
}

impl types::Host for Context {
    fn filesystem_error_code(
        &mut self,
        _err: Resource<wasmtime_wasi_io::streams::Error>,
    ) -> wasmtime::Result<Option<types::ErrorCode>> {
        Ok(None)
    }
}

impl types::HostDescriptor for Context {
    fn read_via_stream(
        &mut self,
        _: Resource<types::Descriptor>,
        _: u64,
    ) -> Denied<Resource<DynInputStream>> {
        denied()
    }

    fn write_via_stream(
        &mut self,
        _: Resource<types::Descriptor>,
        _: u64,
    ) -> Denied<Resource<DynOutputStream>> {
        denied()
    }

    fn append_via_stream(
        &mut self,
        _: Resource<types::Descriptor>,
    ) -> Denied<Resource<DynOutputStream>> {
        denied()
    }

    fn advise(
        &mut self,
        _: Resource<types::Descriptor>,
        _: u64,
        _: u64,
        _: types::Advice,
    ) -> Denied<()> {
        denied()
    }

    fn sync_data(&mut self, _: Resource<types::Descriptor>) -> Denied<()> {
        denied()
    }

    fn get_flags(&mut self, _: Resource<types::Descriptor>) -> Denied<types::DescriptorFlags> {
        denied()
    }

    fn get_type(&mut self, _: Resource<types::Descriptor>) -> Denied<types::DescriptorType> {
        denied()
    }

    fn set_size(&mut self, _: Resource<types::Descriptor>, _: u64) -> Denied<()> {
        denied()
    }

    fn set_times(
        &mut self,
        _: Resource<types::Descriptor>,
        _: types::NewTimestamp,
        _: types::NewTimestamp,
    ) -> Denied<()> {
        denied()
    }

    fn read(&mut self, _: Resource<types::Descriptor>, _: u64, _: u64) -> Denied<(Vec<u8>, bool)> {
        denied()
    }

    fn write(&mut self, _: Resource<types::Descriptor>, _: Vec<u8>, _: u64) -> Denied<u64> {
        denied()
    }

    fn read_directory(
        &mut self,
        _: Resource<types::Descriptor>,
    ) -> Denied<Resource<types::DirectoryEntryStream>> {
        denied()
    }

    fn sync(&mut self, _: Resource<types::Descriptor>) -> Denied<()> {
        denied()
    }

    fn create_directory_at(&mut self, _: Resource<types::Descriptor>, _: String) -> Denied<()> {
        denied()
    }

    fn stat(&mut self, _: Resource<types::Descriptor>) -> Denied<types::DescriptorStat> {
        denied()
    }

    fn stat_at(
        &mut self,
        _: Resource<types::Descriptor>,
        _: types::PathFlags,
        _: String,
    ) -> Denied<types::DescriptorStat> {
        denied()
    }

    fn set_times_at(
        &mut self,
        _: Resource<types::Descriptor>,
        _: types::PathFlags,
        _: String,
        _: types::NewTimestamp,
        _: types::NewTimestamp,
    ) -> Denied<()> {
        denied()
    }

    fn link_at(
        &mut self,
        _: Resource<types::Descriptor>,
        _: types::PathFlags,
        _: String,
        _: Resource<types::Descriptor>,
        _: String,
    ) -> Denied<()> {
        denied()
    }

    fn open_at(
        &mut self,
        _: Resource<types::Descriptor>,
        _: types::PathFlags,
        _: String,
        _: types::OpenFlags,
        _: types::DescriptorFlags,
    ) -> Denied<Resource<types::Descriptor>> {
        denied()
    }

    fn readlink_at(&mut self, _: Resource<types::Descriptor>, _: String) -> Denied<String> {
        denied()
    }

    fn remove_directory_at(&mut self, _: Resource<types::Descriptor>, _: String) -> Denied<()> {
        denied()
    }

    fn rename_at(
        &mut self,
        _: Resource<types::Descriptor>,
        _: String,
        _: Resource<types::Descriptor>,
        _: String,
    ) -> Denied<()> {
        denied()
    }

    fn symlink_at(&mut self, _: Resource<types::Descriptor>, _: String, _: String) -> Denied<()> {
        denied()
    }

    fn unlink_file_at(&mut self, _: Resource<types::Descriptor>, _: String) -> Denied<()> {
        denied()
    }

    fn is_same_object(
        &mut self,
        _: Resource<types::Descriptor>,
        _: Resource<types::Descriptor>,
    ) -> wasmtime::Result<bool> {
        Ok(false)
    }

    fn metadata_hash(
        &mut self,
        _: Resource<types::Descriptor>,
    ) -> Denied<types::MetadataHashValue> {
        denied()
    }

    fn metadata_hash_at(
        &mut self,
        _: Resource<types::Descriptor>,
        _: types::PathFlags,
        _: String,
    ) -> Denied<types::MetadataHashValue> {
        denied()
    }

    fn drop(&mut self, _: Resource<types::Descriptor>) -> wasmtime::Result<()> {
        Ok(())
    }
}

impl types::HostDirectoryEntryStream for Context {
    fn read_directory_entry(
        &mut self,
        _: Resource<types::DirectoryEntryStream>,
    ) -> Denied<Option<types::DirectoryEntry>> {
        denied()
    }

    fn drop(&mut self, _: Resource<types::DirectoryEntryStream>) -> wasmtime::Result<()> {
        Ok(())
    }
}
