// The goals' legacy homes, and the chain that is their file names' numbers. A chain goal is
// `docs/agent/goals/N-<slug>.md`, or the same in the generated goals' subdirectory, plus a sibling
// `.toml` and `.handoff.md` until it is retired; a side goal is the same three files under
// `goals/side/`, with no number. Each becomes `data/goals/<slug>.json` or `data/goals/side/<slug>.json`,
// a handoff beside it, and the numbers across both chain directories become `data/chain.json`, in
// number order.
//
// The goal the driver has installed is the one whose prose `docs/agent/loop-goal.md` is. Its acceptance
// list and handoff are read from `docs/agent/loop-goal.toml` and `docs/agent/handoff.md`, which the
// driver and the sessions keep current, and its own `.toml` and `.handoff.md` are the copies the switch
// installed from, which nothing reads.
//
// The `.md`'s front matter gives `milestone` and `position`, and its H1 after the dash the title. The
// tag `post-parity`, and the tag every generated feature-proof goal carries, name no milestone row. A
// goal carrying one lands in no milestone, so its `milestone` is null and the generated feature-proof
// goals are ordinary goals. A
// retired goal has no `.toml`, so its lists are empty: its checks live on in the floor of every goal
// after it. TOML keys become camelCase, a check's `stage = "N title"` becomes its stage number with the
// title on the goal's `stages`, `[context.stage.N]` folds into that stage's `context`, and the `.md`'s
// `**Does:**` line under `## Stage N — <title>` becomes that stage's `summary`. A check's id
// is its name as a slug, or its kind and what it runs when it has no name, with `-2` and on for a
// repeat, and it never changes after the import.
//
// A handoff's `## Next group` is a lead paragraph, a checklist and what follows it. The note the goal
// generator writes under a generated handoff's H1 is dropped: it names the generator, which this goal
// deletes, and says only that the first session overwrites the file.

import { parse as parseToml } from "smol-toml";
import { chain } from "../schema/chain.ts";
import { goal, sideGoal } from "../schema/goal.ts";
import { handoff, sideHandoff } from "../schema/handoff.ts";
import { exists, extraKeys, frontMatter, list, OLD, text, unwrap, type Importer, type ImportResult, type Unread } from "./lib.ts";

const GOALS = "docs/agent/goals";
const CHAIN_DIRS = [GOALS, `${GOALS}/${OLD}`];
const SIDE = `${GOALS}/side`;
const LIVE = { md: "docs/agent/loop-goal.md", toml: "docs/agent/loop-goal.toml", handoff: "docs/agent/handoff.md" };
const CHAIN_NAME = /^(\d+)-([a-z0-9]+(?:-[a-z0-9]+)*)\.md$/;
const SIDE_NAME = /^([a-z0-9]+(?:-[a-z0-9]+)*)\.md$/;
const H1 = /^# (?:Loop goal \d+|Side goal) — (.+)$/m;
const STAGE_HEADING = /^## Stage (\d+) — /;
const DOES = /^\*\*Does:\*\*\s*/;
/** The front-matter tags that name no row of the plan's milestone table. */
const NO_MILESTONE = ["post-parity", OLD];
/** The note the goal generator writes under a handoff's H1, which no record keeps. */
const GENERATED = new RegExp(`^# Handoff\\s*\\n\\s*\\*\\*Generated by \`python tools\\/${OLD}\\.py --emit-goals\`[\\s\\S]*?\\*\\*(?=\\s*$)`);
const TOP_KEYS = ["files", "context", "check", "docker", "valgrind", "wsl"];
const CONTEXT_KEYS = ["modules", "rules", "adrs", "shapes", "playbook", "plan", "milestones"];
const CHECK_KEYS = [
  "kind", "stage", "name", "argv", "args", "cwd", "tests", "cases", "file", "stream", "want", "exit",
  "stdoutContains", "stderrContains", "minBytes", "minPassing", "needs", "setup", "memoize", "overlap",
];
/** The longest a check id derived from a name grows, cut back to a whole word. */
const ID_MAX = 60;

export interface GoalFiles {
  slug: string;
  md: string;
  /** Null for a retired goal. */
  toml: string | null;
  handoff: string | null;
}

const camel = (k: string) => k.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function camelKeys(v: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(Object.entries(v).map(([k, x]) => [camel(k), x]));
}

export function slugOf(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function checkId(c: Record<string, any>, taken: Set<string>): string {
  const runs = c.file ?? (c.tests ?? c.cases ?? c.argv ?? c.args ?? []).join(" ");
  let base = slugOf(typeof c.name === "string" ? c.name : `${c.kind} ${runs}`);
  if (base.length > ID_MAX) base = base.slice(0, ID_MAX + 1).replace(/-[^-]*$/, "");
  if (base === "") base = "check";
  let id = base;
  for (let n = 2; taken.has(id); n++) id = `${base}-${n}`;
  taken.add(id);
  return id;
}

/** The goal record the files `g` hold, or null with the reason in `unread`. */
export function goalValue(root: string, g: GoalFiles, unread: Unread[]): Record<string, unknown> | null {
  const fm = frontMatter(text(root, g.md));
  if (!fm) {
    unread.push({ path: g.md, reason: "it opens on no front matter, so it names no milestone" });
    return null;
  }
  unread.push(...extraKeys(g.md, "its front matter", Object.fromEntries(fm.fields), ["milestone", "position"]));
  const h1 = H1.exec(fm.body);
  if (!h1) {
    unread.push({ path: g.md, reason: "it has no `# Loop goal N — <title>` or `# Side goal — <title>` H1" });
    return null;
  }
  const tag = fm.fields.get("milestone") ?? "";
  const value: Record<string, unknown> = { title: h1[1]!.trim(), milestone: NO_MILESTONE.includes(tag) ? null : tag };
  if (fm.fields.has("position")) value.position = fm.fields.get("position");
  if (g.toml === null) return { ...value, files: [], context: {}, stages: [], checks: [], env: {} };

  let t: Record<string, any>;
  try {
    t = parseToml(text(root, g.toml)) as Record<string, any>;
  } catch (e) {
    unread.push({ path: g.toml, reason: `it is not TOML: ${(e as Error).message.split("\n")[0]}` });
    return null;
  }
  unread.push(...extraKeys(g.toml, "it", t, TOP_KEYS));
  const { stage: stageContext = {}, ...base } = (t.context ?? {}) as Record<string, any>;
  const context = camelKeys(base);
  unread.push(...extraKeys(g.toml, "its [context]", context, CONTEXT_KEYS));

  const titles = new Map<number, string>();
  const checks: Record<string, unknown>[] = [];
  const taken = new Set<string>();
  for (const raw of (t.check ?? []) as Record<string, any>[]) {
    const m = /^(\d+) (.+)$/.exec(String(raw.stage));
    if (!m) {
      unread.push({ path: g.toml, reason: `check ${JSON.stringify(raw.name ?? raw.file)} has stage ${JSON.stringify(raw.stage)}, not "N title"` });
      continue;
    }
    const number = Number(m[1]);
    const seen = titles.get(number);
    if (seen !== undefined && seen !== m[2]) unread.push({ path: g.toml, reason: `stage ${number} is titled both "${seen}" and "${m[2]}"` });
    if (seen === undefined) titles.set(number, m[2]!);
    const c = camelKeys(raw);
    unread.push(...extraKeys(g.toml, `check ${JSON.stringify(raw.name ?? raw.file)}`, c, CHECK_KEYS));
    checks.push({ ...c, id: checkId(raw, taken), stage: number });
  }
  for (const n of Object.keys(stageContext)) {
    if (!titles.has(Number(n))) unread.push({ path: g.toml, reason: `[context.stage.${n}] is for a stage no check is in` });
  }
  const summaries = stageSummaries(fm.body);
  const stages = [...titles]
    .sort((a, b) => a[0] - b[0])
    .map(([number, title]) => {
      const summary = summaries.get(number);
      const stage: Record<string, unknown> = summary === undefined ? { number, title } : { number, title, summary };
      const own = stageContext[String(number)];
      if (own === undefined) return stage;
      const ctx = camelKeys(own);
      unread.push(...extraKeys(g.toml!, `its [context.stage.${number}]`, ctx, CONTEXT_KEYS));
      return { ...stage, context: ctx };
    });

  const env: Record<string, unknown> = {};
  for (const k of ["docker", "valgrind", "wsl"]) if (t[k] !== undefined) env[k] = camelKeys(t[k]);
  return { ...value, files: t.files ?? [], context, stages, checks, env };
}

/**
 * Each stage's `summary` in the goal's prose `body`, by stage number: the paragraph that opens on
 * `**Does:**` as the first line under the stage's `## Stage N — <title>` heading, unwrapped to one line.
 * A stage whose heading has no such line has no summary.
 */
function stageSummaries(body: string): Map<number, string> {
  const out = new Map<number, string>();
  const lines = body.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const heading = STAGE_HEADING.exec(lines[i]!);
    if (!heading) continue;
    let j = i + 1;
    while (j < lines.length && lines[j]!.trim() === "") j++;
    if (!DOES.test(lines[j] ?? "")) continue;
    const para: string[] = [];
    for (; j < lines.length && lines[j]!.trim() !== ""; j++) para.push(lines[j]!);
    out.set(Number(heading[1]), unwrap(para).replace(DOES, ""));
  }
  return out;
}

/** The installed goal's record, read from the acceptance list the driver keeps current, or null with the reason in `unread`. */
export function installedGoal(root: string, slug: string, md: string, unread: Unread[]): Record<string, unknown> | null {
  return goalValue(root, { slug, md, toml: LIVE.toml, handoff: null }, unread);
}

/**
 * The list that opens `lines`, its items opening on `- ` and each unwrapped to one line, and the
 * lines after it: the list ends at the first line that neither opens nor continues an item.
 */
function listItems(lines: string[]): { items: string[]; rest: string[] } {
  const items: string[] = [];
  let open = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    if (line.startsWith("- ")) {
      items.push(line.slice(2).trim());
      open = true;
    } else if (line.trim() === "") {
      open = false;
    } else if (open && /^\s/.test(line)) {
      items[items.length - 1] += ` ${line.trim()}`;
    } else {
      return { items, rest: lines.slice(i) };
    }
  }
  return { items, rest: [] };
}

/** Where the first `.` that ends a sentence outside backticks is in `s`, or -1. */
function sentenceEnd(s: string): number {
  let code = false;
  for (let i = 0; i < s.length; i++) {
    if (s[i] === "`") code = !code;
    else if (!code && s[i] === "." && (i + 1 === s.length || s[i + 1] === " ")) return i;
  }
  return -1;
}

/**
 * The group's lead line, `**Stage N: title** — one file set: `a`, `b`. More.` The file set is the
 * backticked paths up to the first full stop, and `note` what follows; a file set that is more than
 * a list of paths stays whole in `note`, with `files` empty. A lead that opens on no bold name is
 * all `note`.
 */
function leadOf(lead: string): { stage: number | null; title?: string; files: string[]; note?: string } {
  const m = /^\*\*(?:Stage (\d+): )?(.+?)\*\*\s*(.*)$/s.exec(lead);
  if (!m) return { stage: null, files: [], ...(lead === "" ? {} : { note: lead }) };
  const out = { stage: m[1] === undefined ? null : Number(m[1]), title: m[2]!.replace(/\.$/, "") };
  const rest = m[3]!.replace(/^—\s*/, "");
  const set = /^[Oo]ne file set: (.*)$/.exec(rest);
  if (set) {
    const end = sentenceEnd(set[1]!);
    const clause = end < 0 ? set[1]! : set[1]!.slice(0, end);
    const paths = clause.split(/,\s+(?:and\s+)?|\s+and\s+/);
    if (paths.every((p) => /^`[^`]+`$/.test(p))) {
      const note = end < 0 ? "" : set[1]!.slice(end + 1).trim();
      return { ...out, files: paths.map((p) => p.slice(1, -1)), ...(note === "" ? {} : { note }) };
    }
  }
  return { ...out, files: [], ...(rest === "" ? {} : { note: rest }) };
}

/**
 * The handoff record `path` holds, or null with the reason in `unread`.
 *
 * A seed handoff's state opens on `**Goal N — `, the goal naming itself by its position. A record
 * carries no position, since `data/chain.json` is where one is computed from, so the header names
 * the goal by `slug` instead.
 */
export function handoffValue(root: string, path: string, slug: string, unread: Unread[]): Record<string, unknown> | null {
  const parts = text(root, path).split(/^## /m);
  const head = parts.shift()!.trim().replace(GENERATED, "# Handoff");
  if (head !== "# Handoff") unread.push({ path, reason: "it does not open on `# Handoff` alone" });
  const sections = new Map<string, string[]>();
  for (const p of parts) {
    const [heading, ...body] = p.split("\n");
    sections.set(heading!.trim(), body);
  }
  const extra = [...sections.keys()].filter((k) => !["State", "Next group", "Backlog"].includes(k));
  if (extra.length > 0) unread.push({ path, reason: `its sections ${extra.join(", ")} have no field` });
  const state = sections.get("State");
  const next = sections.get("Next group");
  if (state === undefined || next === undefined) {
    unread.push({ path, reason: "it has no `## State` or no `## Next group`" });
    return null;
  }

  const first = next.findIndex((l) => l.startsWith("- "));
  const lead = leadOf(unwrap(first < 0 ? next : next.slice(0, first)));
  const list = listItems(first < 0 ? [] : next.slice(first));
  const checklist = list.items.map((i) => {
    const m = /^\[( |x)\] (.*)$/.exec(i);
    return m ? { done: m[1] === "x", text: m[2]! } : null;
  });
  const after = unwrap(list.rest);
  const backlog = listItems(sections.get("Backlog") ?? []);
  if (checklist.includes(null) || backlog.rest.some((l) => l.trim() !== "")) {
    unread.push({ path, reason: "a next-group item has no `[ ]` box, or the backlog is not a list" });
    return null;
  }
  const group = { ...lead, items: checklist, ...(after === "" ? {} : { after }) };
  const said = state.join("\n").trim().replace(/^\*\*Goal \d+ —/, `**Goal \`${slug}\` —`);
  return { state: said, next: group, backlog: backlog.items };
}

export const goals: Importer = {
  name: "goals",
  read(root) {
    const out: ImportResult = { records: [], unread: [], files: 0 };
    const liveMd = exists(root, LIVE.md) ? text(root, LIVE.md) : null;
    let live: string | null = null;

    const numbered: { num: number; files: GoalFiles; dir: string }[] = [];
    for (const dir of CHAIN_DIRS) {
      for (const name of list(root, dir)) {
        const m = CHAIN_NAME.exec(name);
        if (!m) continue;
        const stem = `${dir}/${m[1]}-${m[2]}`;
        const has = (p: string) => (exists(root, p) ? p : null);
        const files: GoalFiles = { slug: m[2]!, md: `${stem}.md`, toml: has(`${stem}.toml`), handoff: has(`${stem}.handoff.md`) };
        if (liveMd !== null && text(root, files.md) === liveMd) {
          live = files.slug;
          files.toml = LIVE.toml;
          files.handoff = LIVE.handoff;
        }
        numbered.push({ num: Number(m[1]), files, dir });
      }
    }
    if (liveMd !== null && live === null) out.unread.push({ path: LIVE.md, reason: "it is no goal's prose, so no goal is installed" });

    numbered.sort((a, b) => a.num - b.num);
    const slugs = new Set<string>();
    numbered.forEach((n, i) => {
      if (n.num !== i + 1) out.unread.push({ path: n.files.md, reason: `it is number ${n.num} at chain position ${i + 1}` });
      if (slugs.has(n.files.slug)) out.unread.push({ path: n.files.md, reason: `goal ${n.files.slug} is on the chain twice` });
      slugs.add(n.files.slug);
    });
    out.records.push({ type: chain, id: chain.name, value: numbered.map((n) => n.files.slug), from: GOALS });

    const side = list(root, SIDE).flatMap((name) => {
      const m = SIDE_NAME.exec(name);
      if (!m) return [];
      const stem = `${SIDE}/${m[1]}`;
      const has = (p: string) => (exists(root, p) ? p : null);
      return [{ slug: m[1]!, md: `${stem}.md`, toml: has(`${stem}.toml`), handoff: has(`${stem}.handoff.md`) }];
    });

    const groups = [
      { files: numbered.map((n) => n.files), goalType: goal, handoffType: handoff },
      { files: side, goalType: sideGoal, handoffType: sideHandoff },
    ];
    for (const { files, goalType, handoffType } of groups) {
      for (const g of files) {
        out.files += [g.md, g.toml, g.handoff].filter((p) => p !== null).length;
        const value = goalValue(root, g, out.unread);
        if (value) out.records.push({ type: goalType, id: g.slug, value, from: g.toml ?? g.md });
        if (g.toml !== null && g.handoff === null) out.unread.push({ path: g.toml, reason: "its goal is not retired and has no handoff" });
        if (g.handoff === null) continue;
        const h = handoffValue(root, g.handoff, g.slug, out.unread);
        if (h) out.records.push({ type: handoffType, id: g.slug, value: h, from: g.handoff });
      }
    }
    return out;
  },
};
