blank_issues_enabled: true
contact_links:
  - name: Security problem
    url: https://github.com/novis-lang/novis/security/advisories/new
    about: Tell us in private. Please do not open a public issue.
