// Rendering: the files `bun nv render` writes from the records. A rendered file is committed, carries
// the one generated marker, and is written with LF line ends whatever the platform, so `render
// --check` compares like with like on every machine. A rendered file is never merged by hand: after
// a conflict in one, it is rendered again. A renderer that owns a directory also owns its deletions:
// a file there that it no longer writes is stale.

import { existsSync, mkdirSync, readdirSync, readFileSync, rmdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { ROOT } from "./paths.ts";

export const MARKER = "GENERATED by bun nv render — do not edit";

export interface Output {
  /** Repo-relative. */
  path: string;
  text: string;
}

export interface Renderer {
  name: string;
  render(root: string): Output[] | Promise<Output[]>;
  owns?: Owned;
}

/**
 * A directory whose every file is this renderer's, except the repo-relative names in `keep` under it,
 * and, when `mine` is given, a file it says is not. A file of the renderer's that the render no longer
 * writes is stale, and `bun nv render` deletes it.
 */
export interface Owned {
  dir: string;
  keep: string[];
  mine?: (path: string, root: string) => boolean;
}

/** Every file of an owned directory's renderer that is neither an output nor kept, repo-relative. */
export function orphans(owned: Owned[], outputs: Output[], root: string = ROOT): string[] {
  const written = new Set(outputs.map((o) => o.path));
  const found: string[] = [];
  const walk = (sub: string, own: Owned) => {
    const full = join(root, sub);
    if (!existsSync(full)) return;
    for (const e of readdirSync(full, { withFileTypes: true })) {
      const path = `${sub}/${e.name}`;
      if (e.isDirectory()) walk(path, own);
      else if (written.has(path) || own.keep.includes(path.slice(own.dir.length + 1))) continue;
      else if (own.mine?.(path, root) ?? true) found.push(path);
    }
  };
  for (const own of owned) walk(own.dir, own);
  return found.sort();
}

/** Deletes each of `paths`, and every directory under `dirs` the deletion leaves empty. */
export function removeOrphans(paths: string[], dirs: string[], root: string = ROOT): void {
  for (const path of paths) rmSync(join(root, path));
  const sweep = (full: string, top: boolean) => {
    if (!existsSync(full)) return;
    for (const e of readdirSync(full, { withFileTypes: true })) if (e.isDirectory()) sweep(join(full, e.name), false);
    if (!top && readdirSync(full).length === 0) rmdirSync(full);
  };
  for (const dir of dirs) sweep(join(root, dir), true);
}

/** `text` with LF line ends, no trailing whitespace on a line, and exactly one final newline. */
export function lf(text: string): string {
  return text.replace(/\r\n?/g, "\n").replace(/[ \t]+$/gm, "").replace(/\n*$/, "\n");
}

/**
 * Fills `{{name}}` in `template` from `vars`. A name the template uses and `vars` lacks is an error,
 * so a renamed field fails the render rather than printing an empty hole.
 */
export function fill(template: string, vars: Record<string, string>): string {
  return template.replace(/\{\{\s*([A-Za-z_][A-Za-z0-9_]*)\s*\}\}/g, (_, name: string) => {
    const v = vars[name];
    if (v === undefined) throw new Error(`template names {{${name}}}, which was not given`);
    return v;
  });
}

/**
 * A Markdown file's text with the marker as an HTML comment, which GitHub does not show. It goes
 * after a leading front-matter block, because front matter is only front matter on the first line.
 */
export function markdown(body: string): string {
  const comment = `<!-- ${MARKER} -->\n`;
  const text = lf(body);
  const front = /^---\n[\s\S]*?\n---\n/.exec(text);
  return front ? front[0] + comment + text.slice(front[0].length) : comment + text;
}

export interface Applied {
  /** Files whose text on disk differed, or which did not exist. Written unless `check` was set. */
  stale: string[];
  unchanged: number;
}

/** Writes `outputs`, or with `check` only reports which of them differ from disk. */
export function apply(outputs: Output[], opts: { check: boolean; root?: string }): Applied {
  const root = opts.root ?? ROOT;
  const stale: string[] = [];
  let unchanged = 0;
  const seen = new Set<string>();
  for (const out of outputs) {
    if (seen.has(out.path)) throw new Error(`two renderers write ${out.path}`);
    seen.add(out.path);
    const full = join(root, out.path);
    const text = lf(out.text);
    let before: string | null;
    try {
      before = readFileSync(full, "utf8");
    } catch {
      before = null;
    }
    if (before === text) {
      unchanged++;
      continue;
    }
    stale.push(out.path);
    if (!opts.check) {
      mkdirSync(dirname(full), { recursive: true });
      writeFileSync(full, text);
    }
  }
  return { stale, unchanged };
}
