// `bun nv rules`: the rulebook. It loads it, validates it, renders it and resolves citations against it.
//
//     bun nv rules                     validate, and report what is wrong
//     bun nv rules --check             the CI shape: quiet on success, exit 1 on a finding
//     bun nv rules --render            write docs/rules/*.md and the generated artifacts
//     bun nv rules --render --check    exit 1 if any generated file is stale, write nothing
//     bun nv rules --list              every rule id, one per line
//     bun nv rules --show ID           one rule, metadata and body
//     bun nv rules --locate ID         file:line for peek
//     bun nv rules --citations         every `rule:` citation in the tree, with its resolution
//     bun nv rules --stats             one line per topic: rules, bytes, status split
//
// A rule's structure is its record `data/rules/<topic>/<slug>.json`: status, the decisions behind it,
// flags, and no prose. A rule's prose is the markdown fragment `docs/rules/<topic>/<slug>.md`, which a
// person edits. A rule id is that path: `types/conversion` is `docs/rules/types/conversion.md`, and the
// citation token everywhere is `rule:` and the id. A chapter's place is its topic record's `order`,
// and a rule's place is its position in that record's `rules` list.
//
// `docs/rules/<topic>.md` and `docs/ground-rules.md` are rendered from the two and never edited. `because` points at decision records, and nothing about the reverse direction is
// written by hand. A file that teaches the citation syntax rather than using it carries the marker
// `rules-py:examples`, and its `rule:` tokens are then examples rather than citations. This file
// carries it.
//
// A generated file is written with LF endings. `--render --check` compares text, so a checkout with
// CRLF endings is not stale.

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { FileMemo } from "../lib/filememo.ts";
import { ROOT, rel } from "../lib/paths.ts";
import { ArgError, comparePaths, parseArgs, pyRepr, splitlines } from "../lib/py.ts";
import { load, pathOf, type Loaded } from "../lib/store.ts";
import { rule as ruleRecord } from "../schema/rule.ts";
import { topic as topicRecord } from "../schema/topic.ts";

export const summary = "the rulebook: validate, render, list, show, locate, citations: nv rules [--check] [--render] ...";

const RULES_DIR = join(ROOT, "docs", "rules");

// The generated files name the command that renders them.
const RENDER_COMMAND = "bun nv rules --render";
const generatedHeader = (source: string, topic: string) =>
  `<!-- GENERATED by \`${RENDER_COMMAND}\` from ${source}. Do not edit.\n` +
  `     Edit the prose fragment under docs/rules/${topic}/ or the structure in ${topic}.json. -->\n`;

/** The citation token every file in the repository uses to name a rule. */
export const CITATION = /rule:([a-z0-9][a-z0-9-]*\/[a-z0-9][a-z0-9-]*)/g;
/**
 * The same citation, also consuming the backticks an author writes around it. Without them the
 * rendered chapter would wrap a link in a code span, because only the token inside the ticks was
 * replaced. Both forms become one link.
 */
const LINKIFY = /`rule:([a-z0-9][a-z0-9-]*\/[a-z0-9][a-z0-9-]*)`|rule:([a-z0-9][a-z0-9-]*\/[a-z0-9][a-z0-9-]*)/g;

/** Where a citation may live, as a directory and the extensions under it. Nothing else is scanned. */
const CITATION_GLOBS: [string, string[] | null][] = [
  ["crates", [".rs"]],
  ["docs", [".md"]],
  ["docs", [".toml"]],
  ["tests", null],
  ["tools", [".py"]],
];

/** A file that explains the citation format rather than using it carries this marker. */
const EXAMPLES_ONLY = "rules-py:examples";

/**
 * Where a decision record lives, relative to a generated page in `docs/rules/`. A chapter is written
 * to `docs/rules/<topic>.md`, so a bare `decisions/NNNN.md` would resolve under `docs/rules/`.
 */
const decisionLink = (record: string) => `../decisions/${record}.md`;

interface Rule {
  id: string;
  topic: string;
  slug: string;
  title: string;
  status: string;
  because: string[];
  seeAlso: string[];
  guardedBy: string[];
  bodyPath: string;
}

interface Topic {
  topic: string;
  title: string;
  order: number;
  rules: Rule[];
}

interface Finding {
  where: string;
  what: string;
}

const anchor = (r: Rule) => `${r.topic}-${r.slug}`;
const mdPath = (t: Topic) => join(RULES_DIR, `${t.topic}.md`);
const fmt = (f: Finding) => `  ${f.where}: ${f.what}`;

/** A file's text with every line ending read as `\n`, as Python's text mode reads it. */
function readText(path: string): string {
  return readFileSync(path, "utf8").replace(/\r\n?/g, "\n");
}

/** A string with every leading and trailing `\n` removed. */
function stripNewlines(s: string): string {
  return s.replace(/^\n+|\n+$/g, "");
}

function body(r: Rule): string {
  return existsSync(r.bodyPath) ? stripNewlines(readText(r.bodyPath)) : "";
}

/** `s`'s length in code points, as Python's `len` counts it. */
const codePoints = (s: string) => [...s].length;

export class Rulebook {
  topics: Topic[] = [];
  byId = new Map<string, Rule>();
  findings: Finding[] = [];

  constructor() {
    this.load();
  }

  private fail(where: string, what: string): void {
    this.findings.push({ where, what });
  }

  private load(): void {
    // No rulebook is not an error: every command reads it as "nothing here". A record that fails its
    // schema is a finding, and is left out rather than read half-valid.
    const valid = <T>(rs: Loaded<T>[]) =>
      rs.filter((r) => {
        for (const i of r.issues) this.fail(r.path, i.at ? `${i.at}: ${i.message}` : i.message);
        return r.issues.length === 0;
      });
    const records = new Map(valid(load(ruleRecord)).map((r) => [r.id, r]));
    const listed = new Set<string>();
    for (const rec of valid(load(topicRecord))) {
      const t: Topic = { topic: rec.id, title: rec.value.title, order: rec.value.order, rules: [] };
      rec.value.rules.forEach((rid, order) => {
        const where = `${rec.path}[${order}]`;
        const [topic, slug] = [rid.slice(0, rid.indexOf("/")), rid.slice(rid.indexOf("/") + 1)];
        if (topic !== t.topic) return this.fail(where, `id ${pyRepr(rid)} is not in its own topic ${pyRepr(t.topic)}`);
        if (listed.has(rid)) return this.fail(where, `id ${pyRepr(rid)} is already listed`);
        listed.add(rid);
        const r = records.get(rid);
        if (!r) return this.fail(where, `lists ${pyRepr(rid)}, and ${pathOf(ruleRecord, rid)} is absent`);
        const rule: Rule = {
          id: rid,
          topic,
          slug,
          title: r.value.title,
          status: r.value.status,
          because: r.value.because,

          seeAlso: r.value.seeAlso,
          guardedBy: r.value.guardedBy,
          bodyPath: join(RULES_DIR, topic, `${slug}.md`),
        };
        t.rules.push(rule);
        this.byId.set(rid, rule);
      });
      this.topics.push(t);
    }
    for (const [rid, r] of records) if (!listed.has(rid)) this.fail(r.path, `is a rule no topic lists`);
    this.topics.sort((a, b) => a.order - b.order || (a.topic < b.topic ? -1 : a.topic > b.topic ? 1 : 0));
  }

  /** Everything checkable about the rulebook alone. Citations are `checkCitations`. */
  validate(): Finding[] {
    const out = [...this.findings];
    const seen = new Set<string>();
    for (const t of this.topics) {
      if (t.rules.length === 0) out.push({ where: pathOf(topicRecord, t.topic), what: "declares no rules" });
      for (const r of t.rules) {
        const where = r.id;
        if (!existsSync(r.bodyPath)) out.push({ where, what: `body fragment ${rel(r.bodyPath)} is absent` });
        else if (body(r).trim() === "") out.push({ where, what: "body fragment is empty" });
        seen.add(rel(r.bodyPath).toLowerCase());
        if (r.because.length === 0) out.push({ where, what: "names no decision in `because`" });
        for (const dec of r.because) {
          if (!/^\d{4}$/.test(dec)) out.push({ where, what: `because ${pyRepr(dec)} is not a four-digit record id` });
        }
        for (const other of r.seeAlso) {
          if (!this.byId.has(other)) out.push({ where, what: `seeAlso ${pyRepr(other)} resolves to nothing` });
          else if (other === r.id) out.push({ where, what: "seeAlso names itself" });
        }
        for (const guard of r.guardedBy) {
          if (!existsSync(join(ROOT, guard))) out.push({ where, what: `guardedBy ${pyRepr(guard)} is not a path in the tree` });
        }
      }
    }
    // A fragment nobody declares is a rule that was written and then lost.
    const dirs = readdirSync(RULES_DIR, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name);
    for (const dir of dirs.sort(comparePaths)) {
      const frags = readdirSync(join(RULES_DIR, dir)).filter((n) => n.toLowerCase().endsWith(".md"));
      for (const frag of frags.sort(comparePaths)) {
        const path = rel(join(RULES_DIR, dir, frag));
        if (!seen.has(path.toLowerCase())) out.push({ where: path, what: "is a fragment no rule record declares" });
      }
    }
    return out;
  }

  /** No `rule:` citation anywhere resolves to nothing. */
  checkCitations(): Finding[] {
    const out: Finding[] = [];
    for (const [path, line, rid] of citations()) {
      if (!this.byId.has(rid)) out.push({ where: `${path}:${line}`, what: `cites rule:${rid}, which does not exist` });
    }
    return out;
  }

  // -- rendering ----------------------------------------------------------------------------------

  renderTopic(t: Topic): string {
    const lines = [generatedHeader(`${t.topic}.json`, t.topic), `# ${t.title}\n`];
    const designed = t.rules.filter((r) => r.status === "designed");
    if (designed.length > 0) {
      lines.push(
        `*${designed.length} of ${t.rules.length} rules below are **designed** rather than ` +
          "shipped, and are marked where they appear.*\n",
      );
    }
    for (const r of t.rules) {
      const mark = r.status === "shipped" ? "" : "  *(designed — not yet in the compiler)*";
      lines.push(`<a id="${anchor(r)}"></a>`, `\n## ${r.title}${mark}\n`, `\`rule:${r.id}\`\n`);
      const text = body(r);
      if (text) lines.push(this.linkify(text) + "\n");
      const trailer: string[] = [];
      if (r.seeAlso.length > 0) {
        // Linked, not bare: the trailer's whole job is getting the reader to the next rule.
        const links = r.seeAlso.map((s) => (this.byId.has(s) ? link(this.byId.get(s)!) : `\`rule:${s}\``));
        trailer.push(`See also ${links.join(", ")}.`);
      }
      if (r.because.length > 0) trailer.push(`Decided in ${r.because.map((b) => `[${b}](${decisionLink(b)})`).join(", ")}.`);
      if (trailer.length > 0) lines.push(`<sub>${trailer.join(" ")}</sub>\n`);
    }
    return lines.join("\n").replace(/\n+$/, "") + "\n";
  }

  /** Every citation in prose as a link, leaving fenced code alone. */
  private linkify(text: string): string {
    let fenced = false;
    return splitlines(text)
      .map((line) => {
        if (line.trimStart().startsWith("```")) fenced = !fenced;
        if (fenced) return line;
        return line.replace(LINKIFY, (whole, a: string | undefined, b: string | undefined) => {
          const target = this.byId.get(a ?? b!);
          return target ? link(target) : whole;
        });
      })
      .join("\n");
  }

  renderGroundRules(): string {
    const lines = [
      generatedHeader("docs/rules/", "<topic>"),
      "# The ground rules\n",
      `One line per rule, and the link to the rule that owns it. Generated from \`docs/rules/\` by \`${RENDER_COMMAND}\`.\n`,
    ];
    for (const t of this.topics) {
      if (t.rules.length === 0) continue;
      lines.push(`\n## ${t.title}\n`);
      for (const r of t.rules) {
        const mark = r.status === "shipped" ? "" : " *(designed)*";
        lines.push(`- **${r.title}**${mark} — ${firstSentence(body(r))} ([\`${r.id}\`](rules/${t.topic}.md#${anchor(r)}))`);
      }
    }
    return lines.join("\n").replace(/\n+$/, "") + "\n";
  }


  /** Every generated file and the text it should hold, in the order they are reported. */
  generated(): [string, string][] {
    const out: [string, string][] = this.topics.map((t) => [mdPath(t), this.renderTopic(t)]);
    if (this.topics.length > 0) out.push([join(ROOT, "docs", "ground-rules.md"), this.renderGroundRules()]);
    return out;
  }
}

/** One rule, as the markdown link every generated file points at it with. */
function link(r: Rule): string {
  return `[\`${r.id}\`](${r.topic}.md#${anchor(r)})`;
}

/**
 * The rule in one sentence, for the ground-rules index. The fragment's first prose paragraph is
 * joined before a sentence is taken out of it, so a hard-wrapped sentence keeps its end. A fenced
 * block is skipped rather than read as prose, and a citation is reduced to its bare id, because the
 * row already links to the rule.
 */
function firstSentence(text: string): string {
  const paragraph: string[] = [];
  let fenced = false;
  for (const line of splitlines(text)) {
    const stripped = line.trim();
    if (stripped.startsWith("```")) {
      fenced = !fenced;
      if (paragraph.length > 0) break;
      continue;
    }
    if (fenced) continue;
    if (!stripped || ["|", "<!--", "#", "-", ">", "*"].some((p) => stripped.startsWith(p))) {
      if (paragraph.length > 0) break;
      continue;
    }
    paragraph.push(stripped);
  }
  if (paragraph.length === 0) return "(no prose)";
  const joined = paragraph.join(" ").replace(LINKIFY, (_w, a: string | undefined, b: string | undefined) => `\`${a ?? b}\``);
  const match = /^(.{10,220}?[.!?])(\s|$)/u.exec(joined);
  return match ? match[1]! : [...joined].slice(0, 219).join("").trimEnd() + "…";
}

/** Every file under `dir`, repo-relative, in the order Python's `sorted(ROOT.glob(...))` gives. */
function walk(dir: string): string[] {
  const out: string[] = [];
  const visit = (abs: string) => {
    let entries;
    try {
      entries = readdirSync(abs, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      const path = join(abs, e.name);
      let isDir = e.isDirectory();
      let isFile = e.isFile();
      if (e.isSymbolicLink()) {
        try {
          const st = statSync(path);
          isDir = st.isDirectory();
          isFile = st.isFile();
        } catch {
          continue;
        }
      }
      if (isDir) visit(path);
      else if (isFile) out.push(rel(path));
    }
  };
  visit(join(ROOT, dir));
  return out.sort(comparePaths);
}

const UTF8 = new TextDecoder("utf-8", { fatal: true, ignoreBOM: true });

/** Every `rule:<id>` in the tree, as [path, line number, id]. Each file's citations are memoized against
 * its text. */
function* citations(): Generator<[string, number, string]> {
  const memo = new FileMemo<[number, string][]>("rule-citations", import.meta.path);
  for (const [dir, exts] of CITATION_GLOBS) {
    for (const path of walk(dir)) {
      if (path.split("/").includes("target")) continue;
      if (exts && !exts.some((x) => path.toLowerCase().endsWith(x))) continue;
      let text: string;
      try {
        text = UTF8.decode(readFileSync(join(ROOT, path))).replace(/\r\n?/g, "\n");
      } catch {
        continue;
      }
      if (!text.includes("rule:") || text.includes(EXAMPLES_ONLY)) continue;
      const found = memo.get(path, text, () => {
        const out: [number, string][] = [];
        const lines = splitlines(text);
        for (let i = 0; i < lines.length; i++) for (const m of lines[i]!.matchAll(CITATION)) out.push([i + 1, m[1]!]);
        return out;
      });
      for (const [line, id] of found) yield [path, line, id];
    }
  }
  memo.save();
}

const USAGE = [
  "usage: nv rules [-h] [--check] [--render] [--list] [--show ID] [--locate ID]",
  "                [--citations] [--stats]",
].join("\n");

export async function run(args: string[]): Promise<number> {
  let parsed;
  try {
    parsed = parseArgs(args, {
      flags: ["--check", "--render", "--list", "--citations", "--stats"],
      valued: ["--show", "--locate"],
    });
  } catch (e) {
    if (!(e instanceof ArgError)) throw e;
    console.error(`${USAGE}\nnv rules: error: ${e.message}`);
    return 2;
  }
  const { flags, values } = parsed;
  if (flags.has("--help")) {
    console.log(`${USAGE}\n\nnv rules: ${summary}`);
    return 0;
  }
  const out: string[] = [];
  const flush = () => {
    if (out.length > 0) process.stdout.write(out.join("\n") + "\n");
  };
  const book = new Rulebook();

  if (flags.has("--list")) {
    out.push(...[...book.byId.keys()].sort());
    flush();
    return 0;
  }

  const show = values.get("--show");
  if (show) {
    const r = book.byId.get(show);
    if (!r) {
      console.error(`no such rule: ${show}`);
      return 1;
    }
    out.push(`# ${r.title}   rule:${r.id}`, `status:   ${r.status}`, `because:  ${r.because.join(", ") || "-"}`);

    if (r.seeAlso.length > 0) out.push(`seeAlso:  ${r.seeAlso.join(", ")}`);
    out.push("", body(r));
    flush();
    return 0;
  }

  const locate = values.get("--locate");
  if (locate) {
    const r = book.byId.get(locate);
    if (!r) {
      console.error(`no such rule: ${locate}`);
      return 1;
    }
    console.log(`${rel(r.bodyPath)}:1`);
    return 0;
  }

  if (flags.has("--citations")) {
    for (const [path, line, rid] of citations()) {
      out.push(`${book.byId.has(rid) ? "ok " : "DANGLING"}  ${path}:${line}  rule:${rid}`);
    }
    flush();
    return 0;
  }

  if (flags.has("--stats")) {
    if (book.topics.length === 0) {
      console.log("the rulebook does not exist yet");
      return 0;
    }
    out.push(`${"topic".padEnd(20)} ${"rules".padStart(5)} ${"shipped".padStart(8)} ${"designed".padStart(9)} ${"bytes".padStart(8)}`);
    for (const t of book.topics) {
      const shipped = t.rules.filter((r) => r.status === "shipped").length;
      const size = t.rules.reduce((n, r) => n + codePoints(body(r)), 0);
      const cells = [t.rules.length, shipped, t.rules.length - shipped, size].map(String);
      out.push(`${t.topic.padEnd(20)} ${cells[0]!.padStart(5)} ${cells[1]!.padStart(8)} ${cells[2]!.padStart(9)} ${cells[3]!.padStart(8)}`);
    }
    const total = book.topics.reduce((n, t) => n + t.rules.length, 0);
    out.push("", `${book.topics.length} topics, ${total} rules`);
    flush();
    return 0;
  }

  const findings = [...book.validate(), ...book.checkCitations()];

  if (flags.has("--render")) {
    const stale: string[] = [];
    for (const [path, text] of book.generated()) {
      const current = existsSync(path) ? readText(path) : null;
      if (current === text) continue;
      if (flags.has("--check")) stale.push(rel(path));
      else {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, text);
        console.log(`wrote ${rel(path)}`);
      }
    }
    if (stale.length > 0) {
      console.error(["stale generated files (run --render without --check):", ...stale.map((s) => `  ${s}`)].join("\n"));
      return 1;
    }
  }

  if (findings.length > 0) {
    console.error([`${findings.length} finding(s):`, ...findings.map(fmt)].join("\n"));
    return 1;
  }

  if (!flags.has("--check")) {
    if (book.topics.length === 0) console.log("the rulebook does not exist yet -- migration unit B1 creates it");
    else console.log(`clean: ${book.topics.length} topics, ${book.topics.reduce((n, t) => n + t.rules.length, 0)} rules`);
  }
  return 0;
}
