//! The reference intros, joined at build time.
//!
//! `docs/reference/core/<Class>.md` is the hand-written intro page of one
//! `Core` class, and [`intros`] joins every one of them into a `(class, body)`
//! table with the YAML front matter cut off, which `src/registry.rs` includes
//! as `CoreClass::intro`'s source. Read here rather than `include_str!`'d by
//! hand, so a page is compiled in the day it is written and no class carries a
//! hand-typed path to its own page. `bun nv reference` and the website keep
//! reading the `.md` files; nothing moves.

#![allow(
    clippy::print_stdout,
    reason = "`cargo:` directives on stdout are how a build script talks to Cargo"
)]

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

#[path = "../../tools/build/tests_without_pdb.rs"]
mod tests_without_pdb;

fn main() {
    tests_without_pdb::main();
    let manifest = PathBuf::from(env("CARGO_MANIFEST_DIR"));
    // crates/nvs-stdlib -> the workspace root.
    let workspace = manifest
        .parent()
        .and_then(Path::parent)
        .map_or_else(|| manifest.clone(), Path::to_path_buf);

    println!("cargo:rerun-if-changed=build.rs");
    let reference = workspace.join("docs").join("reference").join("core");
    // A directory, which Cargo walks: a page added tomorrow is a rebuild.
    println!("cargo:rerun-if-changed={}", reference.display());
    let out = PathBuf::from(env("OUT_DIR")).join("intros.rs");
    std::fs::write(&out, intros(&reference))
        .unwrap_or_else(|err| panic!("{}: {err}", out.display()));
}

/// Every page under `dir` as one `(class, body)` row, sorted by class.
///
/// The file name is the class's path with `-` for `\` — `Str.md` is
/// `Core\Str`, `Time-Date.md` is `Core\Time\Date` — which is the spelling
/// `bun nv reference` reads the same tree by. A page naming a class the
/// registry does not hold is not a failure here, since a build script cannot
/// ask the registry; `every_intro_page_names_a_registry_class` in
/// `src/registry.rs` is what fails on one.
fn intros(dir: &Path) -> String {
    let mut pages: Vec<(String, String)> = Vec::new();
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_none_or(|extension| extension != "md") {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            let stem = path
                .file_stem()
                .and_then(|stem| stem.to_str())
                .unwrap_or_default();
            let class = format!("Core\\{}", stem.replace('-', "\\"));
            pages.push((class, body(&read(&path))));
        }
    }
    pages.sort();
    let mut out = String::from(
        "/// One `(class, intro)` per page of `docs/reference/core/`, the front matter cut off,\n\
         /// sorted by class. Generated by `build.rs`.\n\
         pub(crate) const INTROS: &[(&str, &str)] = &[\n",
    );
    for (class, text) in pages {
        let _ = writeln!(out, "    (r\"{class}\", {}),", raw(&text));
    }
    out.push_str("];\n");
    out
}

/// The page below its front matter: what follows the closing `---` line, or
/// the whole page for one that opens with none. Line endings are normalized,
/// so a checkout with CRLF renders the same text as one without.
fn body(text: &str) -> String {
    let text = text.replace("\r\n", "\n");
    let Some(rest) = text.strip_prefix("---\n") else {
        return text.trim().to_owned();
    };
    rest.find("\n---\n")
        .map_or(text.trim(), |at| rest[at + "\n---\n".len()..].trim())
        .to_owned()
}

/// `text` as a Rust raw string literal, fenced with one more `#` than any run
/// the text itself contains.
fn raw(text: &str) -> String {
    let mut longest = 0;
    let mut run = 0;
    for c in text.chars() {
        run = if c == '#' { run + 1 } else { 0 };
        longest = longest.max(run);
    }
    let fence = "#".repeat(longest + 1);
    format!("r{fence}\"{text}\"{fence}")
}

/// An environment variable Cargo always sets for a build script.
fn env(key: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| panic!("cargo sets {key} for a build script"))
}

/// One file, read, or a build failure naming it.
fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|err| panic!("{}: {err}", path.display()))
}
