[package]
name = "nvs-hir"
description = "HIR for Novis: name resolution, namespaces, class graph, symbol table"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
nvs-diagnostics.workspace = true
nvs-syntax.workspace = true
rustc-hash.workspace = true

[lints]
workspace = true
