"""Audit docs/spec/02-php-migration.md against the PHP inventory and the Core member list.

Rule 2 of the library review -- every change gets a migration path -- is only auditable if every PHP
name has a recorded outcome. This script is what records that it does.

  python tools/check-migration.py             # audit; exit 1 on a structural error
  python tools/check-migration.py --report    # audit, then list every unclassified name
  python tools/check-migration.py --min 85    # also exit 1 below 85% classified
  python tools/check-migration.py --seed      # emit rows derived from 01-core-library.md's
                                              # Replaces column, for pasting into the table
  python tools/check-migration.py --help      # this text, without running the audit

`--min` is what the parity program gates on. Coverage on its own is deliberately not an error -- the
table is filled in over several passes and CI going red at 31% would say nothing -- so the threshold
is named by whoever is asserting it. Each of the six goals under docs/agent/goals/ carries its own,
rising to 100 in the last one, which is the program's stop condition. The percentage compared is the
one printed on the `open:` line: classified names over the inventory's function count, rounded the
same way, so a run that prints "85% covered" passes `--min 85` and nothing has to reconcile two
roundings.

Three inputs, each with one job:

  tools/data/php-builtins.txt   the inventory: what PHP has. Generated by tools/dump-php-builtins.php
                                against the oracle build, never edited by hand -- so a name PHP has
                                announced but this build does not carry is in AHEAD_OF_THE_BUILD.
  docs/spec/01-core-library.md  what Novis has. Authoritative for every signature.
  docs/spec/02-php-migration.md the mapping: one row per PHP name, one outcome each.

Structural errors fail the build. An `open` row does not, until the migration file's header says
`Complete: yes` -- so the table can be filled in over several passes without CI going red, while the
count of what is left stays visible on every run.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INVENTORY = ROOT / "tools" / "data" / "php-builtins.txt"
CORE_LIB = ROOT / "docs" / "spec" / "01-core-library.md"
MIGRATION = ROOT / "docs" / "spec" / "02-php-migration.md"

OUTCOMES = {"member", "language", "dropped", "open"}

# Extensions the oracle build does not load, so their functions are absent from the inventory and
# cannot be audited. Named here rather than left implicit: an unaudited extension is a known hole,
# not an empty one. Regenerating the inventory against a fuller build shrinks this list.
#
# **The three database extensions came off it on 2026-08-29**, when the oracle build gained `mysqli`,
# `pgsql` and `sqlite3` and the inventory was regenerated: 925 functions became 1151. That is the
# point at which [ADR 0067](../docs/adr/0067-core-db.md)'s central claim -- one API replaces `PDO`,
# `mysqli`, `pgsql` and `sqlite3` -- stops being an assertion about four APIs and becomes an audit of
# 236 named functions. Everything still on this list is either a Tier 1 extension (`gd`, `intl`,
# `zip`, `exif`) or a subsystem whose replacement is `Core`'s own, and none of it is parity work.
UNAUDITED = [
    "mbstring", "curl", "openssl", "sodium", "sockets", "intl", "gd", "exif", "fileinfo",
    "zip", "posix", "pcntl", "gettext", "ftp", "ldap", "soap",
    "bz2", "xsl", "tidy", "shmop", "sysvsem", "imap", "snmp", "dba", "enchant",
]

# Names a *future* PHP announces that the oracle build does not have yet. A row for one is legitimate --
# the migration table's job is to state Novis's answer to every PHP name, and answering before the
# release is the point of reading a release announcement -- but the inventory cannot list it, so without
# this list the row reads as the typo it looks exactly like.
#
# The alternative is editing tools/data/php-builtins.txt by hand, and that file's whole value is that
# nobody does: it is what a real build reports, so a name in it is a name PHP actually has. A row here
# says instead "this one is ahead of the build", which is a different claim and is allowed to be wrong
# in a way the inventory is not. Each entry names the release it is waiting for, and comes off this list
# when the inventory is regenerated against a build carrying it -- at which point the row is audited
# normally and nothing else changes.
#
# These names are *not* in the denominator. Coverage is classified inventory names over inventory
# functions, so a row here neither raises nor lowers the percentage the parity program's floors gate on;
# it only stops being an error.
AHEAD_OF_THE_BUILD = {
    # [ADR 0124](../docs/adr/0124-php-86-lands-as-four-refusals-and-one-session-rule.md): already
    # `Core\Math::clamp`, and generic over any naturally ordered type rather than over int|float.
    "clamp": "PHP 8.6",
}


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def prose(path: Path) -> str:
    """The file with fenced code blocks removed.

    A ``` fence is three backticks, so leaving them in flips inline-code pairing for everything that
    follows and silently mis-parses the rest of the file -- which is exactly the failure this script
    exists to catch in someone else's document.
    """
    kept: list[str] = []
    fenced = False
    for line in read(path).splitlines():
        if line.lstrip().startswith("```"):
            fenced = not fenced
            continue
        if not fenced:
            kept.append(line)
    return "\n".join(kept)


def php_inventory() -> tuple[list[str], list[str]]:
    """The oracle build's internal functions and types, in file order."""
    functions: list[str] = []
    types: list[str] = []
    bucket: list[str] | None = None
    for line in read(INVENTORY).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line == "[functions]":
            bucket = functions
        elif line == "[types]":
            bucket = types
        elif bucket is not None:
            bucket.append(line)
    return functions, types


CLASS_HEADING = re.compile(r"^#+\s*(?:\d+\.\s*)?`?(Core\\[A-Za-z\\]+)`?")
BACKTICKED = re.compile(r"`([^`]+)`")
PHP_NAME = re.compile(r"[a-z_][a-z0-9_]*")
MEMBER_REF = re.compile(r"(Core\\[A-Za-z\\]+)::([A-Za-z][A-Za-z0-9]*)")


def core_surface() -> tuple[set[str], set[str]]:
    """Every `Core\\X` class named in the spec, and every backticked bare word in it.

    The second set is deliberately loose: the spec states some members in prose (`Core\\Bytes`'s
    roster, `Core\\Validate`'s predicates, all of Part II), so demanding a table row per member
    would fail on the file's own valid shapes. What this catches is the case that actually
    happens -- a member renamed in the spec while the migration table still names the old one.
    """
    classes: set[str] = set()
    words: set[str] = set()
    for span in BACKTICKED.findall(prose(CORE_LIB)):
        for cls in re.findall(r"Core\\[A-Za-z\\]+", span):
            classes.add(cls)
        for cls, member in MEMBER_REF.findall(span):
            classes.add(cls)
            words.add(member)
        bare = span.strip()
        if re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", bare):
            words.add(bare)
        head = re.match(r"([A-Za-z][A-Za-z0-9]*)\s*\(", bare)
        if head:
            words.add(head.group(1))
        arrow = re.match(r"\$\w+->([A-Za-z][A-Za-z0-9]*)", bare)
        if arrow:
            words.add(arrow.group(1))
    return classes, words


ROW = re.compile(r"^\|\s*`([^`]+)`\s*\|\s*([a-z]+)\s*\|(.*)\|\s*$")


def migration_rows() -> tuple[dict[str, tuple[str, str]], list[str], bool]:
    """Rows keyed by PHP name, plus duplicates, plus whether the file claims completeness."""
    rows: dict[str, tuple[str, str]] = {}
    duplicates: list[str] = []
    complete = False
    for line in read(MIGRATION).splitlines():
        if line.startswith("**Complete:**"):
            complete = "yes" in line.lower()
        match = ROW.match(line.rstrip())
        if not match:
            continue
        name, outcome, note = match.group(1), match.group(2), match.group(3).strip()
        if name in rows:
            duplicates.append(name)
        rows[name] = (outcome, note)
    return rows, duplicates, complete


def seed() -> None:
    """Emit rows derived from the Replaces column, for a human to check and paste."""
    functions, _ = php_inventory()
    known = set(functions)
    text = prose(CORE_LIB)
    section = ""
    derived: dict[str, str] = {}
    for line in text.splitlines():
        if line.startswith("#"):
            found = re.search(r"`(Core\\[A-Za-z\\]+)`", line)
            if found:
                section = found.group(1)
            continue
        spans = BACKTICKED.findall(line)
        if not spans:
            continue
        # The target is whatever the line is *about*: a table row's first cell, a bullet's leading
        # class, or failing both the section this line sits in.
        target = section
        lead = spans[0].strip()
        if line.startswith("|"):
            first = [c.strip() for c in line.split("|")][1]
            head = BACKTICKED.search(first)
            if head:
                name = head.group(1).strip()
                qualified = re.match(r"(Core\\[A-Za-z\\]+)(?:::|$)", name)
                if qualified:
                    target = name.split("(")[0].strip("`")
                elif "::" in name:
                    target = "Core\\" + name
                elif re.fullmatch(r"[A-Za-z][A-Za-z0-9]*(\s*/\s*[A-Za-z][A-Za-z0-9]*)?", name):
                    target = f"{section}::{name.split('/')[0].strip()}" if section else name
        elif line.startswith("- ") and lead.startswith("Core\\"):
            target = lead
        for span in spans:
            for candidate in PHP_NAME.findall(span):
                if candidate in known and candidate not in derived:
                    derived[candidate] = target
    for name in sorted(derived):
        target = derived[name]
        cell = f"`{target}`" if target else ""
        print(f"| `{name}` | member | {cell} |")
    print(f"\n# {len(derived)} of {len(functions)} inventory functions derived", file=sys.stderr)


def main() -> int:
    # Before the audit, not after: without this the tool answered `--help` by running the whole
    # inventory, so `--report`, `--seed` and `--min` were invisible to anything -- a session or a
    # mechanical audit -- that asks a script what it takes.
    if any(a in ("-h", "--help") for a in sys.argv[1:]):
        print(__doc__.strip())
        return 0

    if "--seed" in sys.argv:
        seed()
        return 0

    functions, types = php_inventory()
    classes, words = core_surface()
    rows, duplicates, complete = migration_rows()

    errors: list[str] = []
    for name in duplicates:
        errors.append(f"duplicate row: {name}")
    for name, (outcome, note) in rows.items():
        if outcome not in OUTCOMES:
            errors.append(f"{name}: unknown outcome {outcome!r}, expected one of {sorted(OUTCOMES)}")
        if outcome in {"member", "dropped", "language"} and not note:
            errors.append(f"{name}: outcome {outcome} with an empty replacement cell")
        for cls, member in MEMBER_REF.findall(note):
            if cls not in classes:
                errors.append(f"{name}: names {cls}, which 01-core-library.md does not")
            elif member not in words:
                errors.append(f"{name}: names {cls}::{member}, which 01-core-library.md does not")

    inventory = set(functions)
    unknown = sorted(
        n for n in rows
        if n not in inventory and n not in set(types) and n not in AHEAD_OF_THE_BUILD
    )
    for name in unknown:
        errors.append(f"row for {name!r}, which the inventory does not list -- typo, or a stale row")

    # A name with no row and a name whose row says `open` are the same thing: undecided.
    unclassified = [f for f in functions if rows.get(f, ("open", ""))[0] == "open"]

    covered = round(100 * (1 - len(unclassified) / max(len(functions), 1)))
    print(f"inventory: {len(functions)} functions, {len(types)} types "
          f"({INVENTORY.relative_to(ROOT)})")
    print(f"rows:      {len(rows)}  classified: {len(rows) - len([r for r in rows.values() if r[0] == 'open'])}")
    print(f"open:      {len(unclassified)}  ({covered}% covered)")
    print(f"unaudited extensions (absent from this build): {', '.join(UNAUDITED)}")
    ahead = sorted(n for n in rows if n in AHEAD_OF_THE_BUILD)
    if ahead:
        print("ahead of the build (answered, not yet in the inventory): "
              + ", ".join(f"{n} ({AHEAD_OF_THE_BUILD[n]})" for n in ahead))

    if "--report" in sys.argv and unclassified:
        print("\nunclassified:")
        for name in unclassified:
            print(f"  {name}")

    if errors:
        print(f"\n{len(errors)} structural error(s):")
        for error in errors[:80]:
            print(f"  {error}")
        if len(errors) > 80:
            print(f"  ... and {len(errors) - 80} more")
        return 1

    if complete and unclassified:
        print(f"\nheader says Complete: yes, but {len(unclassified)} names are unclassified")
        return 1

    # `--min N` -- the parity program's gate. Compared against the same rounded figure the `open:`
    # line prints, so a run that says "85% covered" passes `--min 85`.
    if "--min" in sys.argv:
        at = sys.argv.index("--min")
        if at + 1 >= len(sys.argv):
            print("\n--min needs a percentage, e.g. --min 85")
            return 2
        try:
            floor = int(sys.argv[at + 1])
        except ValueError:
            print(f"\n--min takes a whole percentage, not {sys.argv[at + 1]!r}")
            return 2
        if covered < floor:
            print(f"\n{covered}% covered, below the {floor}% this run asserts "
                  f"-- {len(unclassified)} name(s) still unclassified, `--report` lists them")
            return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
