<?php
// Emits the inventory docs/spec/02-php-migration.md is audited against: every internal function and
// every internal class this PHP build exposes, one per line, sorted, with a provenance header.
//
// Run it against the PHP the repository already uses as its differential oracle, with every extension
// the committed inventory was taken with. On Windows that PHP ships `fileinfo` and `zip` as DLLs its
// `php.ini` does not enable, so they are loaded on the command line rather than by editing the machine's
// configuration:
//   php -d extension=php_fileinfo.dll -d extension=php_zip.dll tools/dump-php-builtins.php \
//       > tools/data/php-builtins.txt
//
// A run that omits one of them writes a *smaller* inventory, and `bun nv migration` reads that as
// rows for names PHP does not have. The `# extensions:` header line is what a regenerated file must be
// compared against: it is the list the audit's denominator was taken from.
//
// The result is committed. It is an inventory, never a decision — what Novis does with each name is
// docs/spec/02-php-migration.md, and `bun nv migration` compares the two.

$functions = get_defined_functions()['internal'];
sort($functions, SORT_STRING);

$classes = array_filter(get_declared_classes(), function (string $c): bool {
    return (new ReflectionClass($c))->isInternal();
});
$interfaces = array_filter(get_declared_interfaces(), function (string $c): bool {
    return (new ReflectionClass($c))->isInternal();
});
$types = array_merge($classes, $interfaces);
sort($types, SORT_STRING);

$extensions = get_loaded_extensions();
sort($extensions, SORT_STRING);

echo "# Generated by tools/dump-php-builtins.php - do not edit by hand.\n";
echo "# php: " . PHP_VERSION . "\n";
echo "# extensions: " . implode(" ", $extensions) . "\n";
echo "# functions: " . count($functions) . "  types: " . count($types) . "\n";
echo "\n[functions]\n";
foreach ($functions as $name) {
    echo $name . "\n";
}
echo "\n[types]\n";
foreach ($types as $name) {
    echo $name . "\n";
}
