<?php
// Emits the inventory docs/spec/02-php-migration.md is audited against: every internal function and
// every internal class this PHP build exposes, one per line, sorted, with a provenance header.
//
// Run it against the PHP the repository already uses as its differential oracle:
//   php tools/dump-php-builtins.php > tools/data/php-builtins.txt
//
// The result is committed. It is an inventory, never a decision — what MWL does with each name is
// docs/spec/02-php-migration.md, and tools/check-migration.py compares the two.

$functions = get_defined_functions()['internal'];
sort($functions, SORT_STRING);

$classes = array_filter(get_declared_classes(), function (string $c): bool {
    return (new ReflectionClass($c))->isInternal();
});
$interfaces = array_filter(get_declared_interfaces(), function (string $c): bool {
    return (new ReflectionClass($c))->isInternal();
});
$types = array_merge($classes, $interfaces);
sort($types, SORT_STRING);

$extensions = get_loaded_extensions();
sort($extensions, SORT_STRING);

echo "# Generated by tools/dump-php-builtins.php - do not edit by hand.\n";
echo "# php: " . PHP_VERSION . "\n";
echo "# extensions: " . implode(" ", $extensions) . "\n";
echo "# functions: " . count($functions) . "  types: " . count($types) . "\n";
echo "\n[functions]\n";
foreach ($functions as $name) {
    echo $name . "\n";
}
echo "\n[types]\n";
foreach ($types as $name) {
    echo $name . "\n";
}
