#!/usr/bin/env python3
"""Generate every crate's `[lints]` table from the workspace's, and check it stayed that way.

`[workspace.lints]` in the root manifest is the one home for this repository's
lint policy. Most crates inherit it with `[lints] workspace = true` and there is
nothing to generate. The crates that hold `unsafe` cannot: the workspace pins
`unsafe_code = "forbid"`, which no inner `#[allow]` can relax, so they need
`deny` instead — and cargo refuses to let a manifest inherit the workspace table
and override one entry of it:

    error: cannot override `workspace.lints` in `lints`, either remove the
           overrides or `lints.workspace = true` and manually specify the lints

So those crates must restate the whole table, and a restated table drifts. It
already had: `benches/abi-probe` was missing seven of the lints every other
crate carries, with nothing to say whether that was a decision or an omission.
This script is what makes the copies copies — one home, mechanically enforced,
the same shape as `tools/nv/cmd/gen-attribution.ts`.

    python tools/lints.py            # rewrite the generated tables
    python tools/lints.py --check    # exit 1 if any has drifted (CI, nv verify)

`UNSAFE_CRATES` below is the roster of manifests that may override, and the
reason each one needs to. It is the one home for that list: `docs/plan/design.md`
§ *Unsafe policy* points here rather than restating it, because the prose copy
of the roster is exactly what went stale — it named four crates while seven
carried `unsafe`.

Two properties are worth knowing before changing anything here:

* **`unsafe_code` is the only permitted delta.** A crate on the roster gets the
  workspace table with that one key changed to `deny`; it cannot quietly weaken
  a second lint, because `--check` compares the rendered table byte for byte
  against what `--write` would produce. A crate that genuinely needs another
  exception records it in `EXCEPTIONS`, with a reason, where it is visible —
  which is the whole difference between that roster and an omitted line.

* **It fails closed in both directions.** A crate off the roster that carries
  its own `[lints]` table is an error, not a silently tolerated override; a
  crate on neither footing — no table at all — is an error too, so a new crate
  cannot join the workspace with no lint policy by saying nothing.
"""

from __future__ import annotations

import argparse
import difflib
import fnmatch
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: The manifests that may override the workspace table, and why each must.
#: `docs/plan/design.md` § *Unsafe policy* reaches this list rather than holding
#: its own copy. A crate joins it only with an ADR, per that section.
UNSAFE_CRATES: dict[str, str] = {
    "crates/nvs-runtime": "the helper ABI's `extern \"C\"` entry points, the request arena "
    "and the tagged-value representation decode raw pointers",
    "crates/nvs-stdlib": "every `Core` member is an `rule:errors/propagation` helper entry "
    "point, and therefore an `extern \"C\"` function over raw pointers",
    "crates/nvs-codegen": "JIT page mapping, and transmuting a compiled code pointer to a "
    "callable function pointer",
    "crates/nvs-host": "the coroutine stack switcher's one deref of the opaque yielder, and "
    "CPU affinity through the platform API",
    "crates/nvs-config": "the process environment is read through `std::env`, whose accessors "
    "are `unsafe` in edition 2024",
    "crates/nvs-cli": "the process environment again, at the one place the binary sets it "
    "before handing control to the runtime",
    "benches/abi-probe": "it calls JIT-compiled code to measure it; `publish = false` and no "
    "shipped crate depends on it, so it does not widen the runtime's unsafe surface",
}

#: Per-manifest lint exceptions beyond `unsafe_code`, each with the reason it is
#: not simply the workspace value. An entry here is a hole in the policy and has
#: to be argued for; what it buys over the silent omission it replaces is that
#: the hole is written down, in one place, next to its reason.
EXCEPTIONS: dict[str, dict[str, dict[str, object]]] = {
    # This crate builds Cranelift IR to call, so it casts host addresses and
    # slot indices into the `i64` and `i32` an `iconst` takes. The cast is the
    # measurement: a probe that widened through `try_from` would be measuring
    # the conversion rather than the ABI. Nine sites, all in `src/lib.rs`, and
    # `publish = false` keeps them out of anything shipped. The stricter fix is
    # a per-site `#[expect(..., reason = ...)]`, which would put the argument
    # next to each cast instead of here.
    "benches/abi-probe": {
        "clippy": {
            "cast_possible_truncation": "allow",
            "cast_possible_wrap": "allow",
            "cast_sign_loss": "allow",
        }
    },
}

MARKER = "# @generated by tools/lints.py -- edit `[workspace.lints]` in the root manifest."
PREAMBLE = (
    MARKER,
    "# This crate is on that script's `UNSAFE_CRATES` roster, so it restates the",
    "# workspace table with `unsafe_code = \"deny\"`: cargo will not let a manifest",
    "# inherit `[workspace.lints]` and override one entry, and `forbid` is not",
    "# something an individual `#[allow(unsafe_code, reason = ...)]` can relax.",
)


def render_value(value: object) -> str:
    """Format one lint value the way the root manifest writes it."""
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, dict):
        inner = ", ".join(f"{k} = {render_value(v)}" for k, v in value.items())
        return f"{{ {inner} }}"
    raise SystemExit(f"lints.py: cannot render lint value {value!r}")


def workspace_lints(manifest: dict) -> dict[str, dict[str, object]]:
    lints = manifest.get("workspace", {}).get("lints")
    if not lints:
        raise SystemExit("lints.py: the root manifest has no [workspace.lints] table")
    return lints


def members(manifest: dict) -> list[Path]:
    """Every workspace member that has a manifest, from the root's own globs."""
    workspace = manifest.get("workspace", {})
    excluded = {e.rstrip("/") for e in workspace.get("exclude", [])}
    found: list[Path] = []
    for pattern in workspace.get("members", []):
        for path in sorted(ROOT.glob(pattern)):
            rel = path.relative_to(ROOT).as_posix()
            if any(fnmatch.fnmatch(rel, ex) or rel == ex for ex in excluded):
                continue
            if (path / "Cargo.toml").is_file():
                found.append(path)
    return found


def expected_tables(
    ws_lints: dict[str, dict[str, object]], rel: str
) -> dict[str, dict[str, object]]:
    """The lint tables `rel` must carry: the workspace's, with its own deltas applied."""
    tables = {group: dict(entries) for group, entries in ws_lints.items()}
    tables["rust"]["unsafe_code"] = "deny"
    for group, entries in EXCEPTIONS.get(rel, {}).items():
        tables.setdefault(group, {}).update(entries)
    return tables


def render_region(tables: dict[str, dict[str, object]]) -> str:
    lines = list(PREAMBLE)
    for group, entries in tables.items():
        lines.append("")
        lines.append(f"[lints.{group}]")
        lines += [f"{key} = {render_value(value)}" for key, value in entries.items()]
    return "\n".join(lines) + "\n"


def split_manifest(text: str) -> tuple[str, str]:
    """Return the manifest above its lint region, and the region itself.

    The region runs from this script's marker — or, on a manifest it has not
    generated yet, the first `[lints` header — to the end of the file. Every
    manifest in the workspace ends with its lint tables, and the hand-written
    comment that explains why a crate needs `unsafe` sits *above* the region and
    is never touched.
    """
    lines = text.splitlines(keepends=True)
    for index, line in enumerate(lines):
        if line.startswith(MARKER) or line.startswith("[lints"):
            return "".join(lines[:index]), "".join(lines[index:])
    return text, ""


def check_or_write(write: bool) -> int:
    root_manifest = tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))
    ws_lints = workspace_lints(root_manifest)
    problems: list[str] = []
    rewritten: list[str] = []

    known = set(UNSAFE_CRATES)
    for path in members(root_manifest):
        rel = path.relative_to(ROOT).as_posix()
        manifest_path = path / "Cargo.toml"
        text = manifest_path.read_text(encoding="utf-8")
        parsed = tomllib.loads(text)
        declared = parsed.get("lints", {})

        if rel not in UNSAFE_CRATES:
            if not declared.get("workspace"):
                problems.append(
                    f"{rel}/Cargo.toml: carries its own [lints] table but is not on "
                    f"lints.py's UNSAFE_CRATES roster. Inherit with `[lints] workspace = true`, "
                    f"or add it to the roster with the reason it needs `unsafe`."
                    if declared
                    else f"{rel}/Cargo.toml: has no [lints] table at all. Add "
                    f"`[lints]` / `workspace = true`."
                )
            continue

        known.discard(rel)
        head, region = split_manifest(text)
        wanted = render_region(expected_tables(ws_lints, rel))
        if region == wanted:
            continue
        if write:
            manifest_path.write_text(head.rstrip("\n") + "\n\n" + wanted, encoding="utf-8")
            rewritten.append(rel)
        else:
            diff = difflib.unified_diff(
                region.splitlines(), wanted.splitlines(),
                fromfile=f"{rel}/Cargo.toml", tofile="generated", lineterm="",
            )
            problems.append(f"{rel}/Cargo.toml has drifted:\n" + "\n".join(diff))

    for missing in sorted(known):
        problems.append(
            f"{missing}: on lints.py's UNSAFE_CRATES roster but is not a workspace member. "
            f"Remove the entry, or fix the path."
        )

    if problems:
        print("\n\n".join(problems), file=sys.stderr)
        print(
            f"\n{len(problems)} problem(s). `python tools/lints.py` rewrites what it can.",
            file=sys.stderr,
        )
        return 1
    if write:
        print(f"lints: rewrote {len(rewritten)}" if rewritten else "lints: already current")
    else:
        print(f"lints: {len(UNSAFE_CRATES)} generated tables current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true",
        help="exit 1 if any generated table has drifted, changing nothing",
    )
    args = parser.parse_args()
    return check_or_write(write=not args.check)


if __name__ == "__main__":
    sys.exit(main())
