#!/usr/bin/env python3
"""The rulebook: load it, validate it, render it, resolve a citation against it.

`docs/rules/` is the one home for every rule that is currently true. A rule's *structure* lives in
`docs/rules/<topic>.json` -- ids, status, the decisions behind it, flags -- and carries no prose, so
there is nothing in it to escape. A rule's *prose* is a markdown fragment at
`docs/rules/<topic>/<slug>.md`, which is real markdown a person edits directly. `docs/rules/<topic>.md`
is generated from the two and is never edited.

    python tools/rules.py                 validate, and report what is wrong
    python tools/rules.py --check         the CI shape: quiet on success, exit 1 on a finding
    python tools/rules.py --render        write docs/rules/*.md and the generated artifacts
    python tools/rules.py --render --check  exit 1 if any generated file is stale, write nothing
    python tools/rules.py --list          every rule id, one per line
    python tools/rules.py --show ID       one rule, metadata and body
    python tools/rules.py --locate ID     file:line for peek.py
    python tools/rules.py --citations     every `rule:` citation in the tree, with its resolution
    python tools/rules.py --stats         one line per topic: rules, bytes, status split

A RULE ID IS A PATH

`types/conversion` is `docs/rules/types/conversion.md`. The id is namespaced by its topic, so two
topics cannot collide on one -- which is what lets the migration author many topics in parallel
without a lock. The citation token, everywhere in the repository, is `rule:types/conversion`;
`grep -rn 'rule:' ` finds every one of them, and that is what makes the migration's gate cheap.

A chapter's place is the `order` in `_index.json`; a rule's place is its position in the topic's
`rules` array, and there is no `order` field on a rule. Both read from the ground up rather than by
when the decision landed, which is a thing no check can measure: the scheme, and where a new rule
goes under it, is `docs/agent/conventions.md` -- *Where a rule sits in the order*.

WHAT IS GENERATED FROM THIS, AND WHY IT IS NOT MAINTAINED BY HAND

`docs/rules/<topic>.md`, `docs/ground-rules.md` and `docs/divergences.md` are all derived here.
`docs/novis.md` is `tools/reference.py`'s, filtered to rules whose `status` is `shipped`, so that
file keeps the property that every line in it runs while the rulebook carries the whole designed
surface. Nothing about the relationship between a rule and the decisions behind it is written by
hand: `because` points at decision records, and the reverse index is derived.

A file that teaches this spelling rather than using it carries the marker `rules-py:examples`
anywhere in its text, and its `rule:` tokens are then read as examples rather than as citations.
This docstring carries it, which is why its own `rule:types/conversion` above is not a finding.

`--check` and `--render --check` are CI's `docs` job, and `tools/session.py`'s `rulebook_findings`
runs both in-process for any session that has edited `docs/rules/` -- so a wrap cannot commit a
renamed rule with its citations left dangling, or a fragment with its chapter left un-rendered.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = ROOT / "docs" / "rules"
INDEX = RULES_DIR / "_index.json"

GENERATED_HEADER = (
    "<!-- GENERATED by `python tools/rules.py --render` from {source}. Do not edit.\n"
    "     Edit the prose fragment under docs/rules/{topic}/ or the structure in {topic}.json. -->\n"
)

#: The citation token every file in the repository uses to name a rule.
CITATION = re.compile(r"rule:([a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]*)")

#: The same citation, but also consuming the backticks an author naturally writes around it. A
#: fragment saying ``rule:types/conversion`` in ticks would otherwise render as a code span wrapping
#: a link -- a literal ``[`types/conversion`](types.md#…)`` -- because only the token inside the
#: ticks was substituted. The B1 pilot hit that 35 times in one chapter. Both spellings are read,
#: and both become one link.
LINKIFY = re.compile(
    r"`rule:([a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]*)`"
    r"|rule:([a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]*)"
)

#: Where a citation may live. Everything else is not scanned.
CITATION_GLOBS = ("crates/**/*.rs", "docs/**/*.md", "docs/**/*.toml", "tests/**/*", "tools/**/*.py")

#: A file that *explains* the citation format rather than using it carries this marker anywhere in
#: its text, and its `rule:` tokens are read as examples. Without it, every document that teaches
#: the spelling would report its own examples as dangling citations -- which is what this file did
#: on the first run.
EXAMPLES_ONLY = "rules-py:examples"

def decision_link(record: str) -> str:
    """Where a decision record lives, relative to a generated page in `docs/rules/`.

    The `../` is the whole content of this function and the reason it is one: a chapter is written
    to `docs/rules/<topic>.md`, so a bare `decisions/NNNN.md` resolves to `docs/rules/decisions/`
    and every one of them is a dead link. `check-links.py` catches that, and did.
    """
    return f"../decisions/{record}.md"


STATUSES = ("shipped", "designed")
ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]*$")
TOPIC_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")


@dataclass
class Rule:
    id: str
    topic: str
    slug: str
    title: str
    status: str
    because: list[str]
    diverges: str | None
    see_also: list[str]
    guarded_by: list[str]
    body_path: Path
    order: int

    @property
    def anchor(self) -> str:
        return f"{self.topic}-{self.slug}"

    def body(self) -> str:
        if not self.body_path.exists():
            return ""
        return self.body_path.read_text(encoding="utf-8").strip("\n")


@dataclass
class Topic:
    topic: str
    title: str
    order: int
    rules: list[Rule] = field(default_factory=list)

    @property
    def json_path(self) -> Path:
        return RULES_DIR / f"{self.topic}.json"

    @property
    def md_path(self) -> Path:
        return RULES_DIR / f"{self.topic}.md"


@dataclass
class Finding:
    where: str
    what: str

    def __str__(self) -> str:
        return f"  {self.where}: {self.what}"


class Rulebook:
    def __init__(self) -> None:
        self.topics: list[Topic] = []
        self.by_id: dict[str, Rule] = {}
        self.findings: list[Finding] = []
        self._load()

    # -- loading ---------------------------------------------------------------

    def _fail(self, where: str, what: str) -> None:
        self.findings.append(Finding(where, what))

    def _load(self) -> None:
        if not INDEX.exists():
            # The rulebook does not exist yet. That is the state before migration unit B1, and it
            # is not an error -- every command below degrades to "nothing here".
            return
        try:
            index = json.loads(INDEX.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            self._fail(str(INDEX.relative_to(ROOT)), f"is not valid JSON: {exc}")
            return

        for entry in index.get("topics", []):
            topic = entry.get("topic", "")
            if not TOPIC_RE.match(topic):
                self._fail("_index.json", f"topic name {topic!r} is not lowercase-kebab")
                continue
            t = Topic(topic=topic, title=entry.get("title", topic), order=entry.get("order", 0))
            self._load_topic(t)
            self.topics.append(t)
        self.topics.sort(key=lambda t: (t.order, t.topic))

    def _load_topic(self, t: Topic) -> None:
        if not t.json_path.exists():
            self._fail("_index.json", f"names topic {t.topic!r} and {t.json_path.name} is absent")
            return
        try:
            data = json.loads(t.json_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            self._fail(t.json_path.name, f"is not valid JSON: {exc}")
            return

        for order, raw in enumerate(data.get("rules", [])):
            rid = raw.get("id", "")
            where = f"{t.json_path.name}[{order}]"
            if not ID_RE.match(rid):
                self._fail(where, f"id {rid!r} is not `<topic>/<slug>`")
                continue
            topic, slug = rid.split("/", 1)
            if topic != t.topic:
                self._fail(where, f"id {rid!r} is not in its own topic {t.topic!r}")
                continue
            if rid in self.by_id:
                self._fail(where, f"id {rid!r} is already defined")
                continue
            status = raw.get("status", "")
            if status not in STATUSES:
                self._fail(where, f"status {status!r} is not one of {'/'.join(STATUSES)}")
            rule = Rule(
                id=rid,
                topic=topic,
                slug=slug,
                title=raw.get("title", slug),
                status=status,
                because=[str(b) for b in raw.get("because", [])],
                diverges=raw.get("divergesFromPhp"),
                see_also=[str(s) for s in raw.get("seeAlso", [])],
                guarded_by=[str(g) for g in raw.get("guardedBy", [])],
                body_path=RULES_DIR / topic / f"{slug}.md",
                order=order,
            )
            t.rules.append(rule)
            self.by_id[rid] = rule

    # -- validation ------------------------------------------------------------

    def validate(self) -> list[Finding]:
        """Everything checkable about the rulebook alone. Citations are `check_citations`."""
        out = list(self.findings)
        seen_fragments: set[Path] = set()

        for t in self.topics:
            if not t.rules:
                out.append(Finding(t.json_path.name, "declares no rules"))
            for r in t.rules:
                where = r.id
                if not r.body_path.exists():
                    out.append(Finding(where, f"body fragment {self._rel(r.body_path)} is absent"))
                elif not r.body().strip():
                    out.append(Finding(where, "body fragment is empty"))
                seen_fragments.add(r.body_path)

                if not r.because:
                    out.append(Finding(where, "names no decision in `because`"))
                for dec in r.because:
                    if not re.match(r"^\d{4}$", dec):
                        out.append(Finding(where, f"because {dec!r} is not a four-digit record id"))
                for other in r.see_also:
                    if other not in self.by_id:
                        out.append(Finding(where, f"seeAlso {other!r} resolves to nothing"))
                    elif other == r.id:
                        out.append(Finding(where, "seeAlso names itself"))
                for guard in r.guarded_by:
                    if not (ROOT / guard).exists():
                        out.append(Finding(where, f"guardedBy {guard!r} is not a path in the tree"))

        # A fragment nobody declares is a rule that was written and then lost.
        for topic_dir in sorted(p for p in RULES_DIR.glob("*") if p.is_dir()):
            for frag in sorted(topic_dir.glob("*.md")):
                if frag not in seen_fragments:
                    out.append(
                        Finding(self._rel(frag), "is a fragment no rule in the topic's JSON declares")
                    )
        return out

    def check_citations(self) -> list[Finding]:
        """Gate check 1: no `rule:` citation anywhere resolves to nothing."""
        out: list[Finding] = []
        for path, line_no, rid in self.iter_citations():
            if rid not in self.by_id:
                out.append(Finding(f"{self._rel(path)}:{line_no}", f"cites rule:{rid}, which does not exist"))
        return out

    def iter_citations(self):
        """Every `rule:<id>` in the tree, as (path, line number, id)."""
        for pattern in CITATION_GLOBS:
            for path in sorted(ROOT.glob(pattern)):
                if not path.is_file() or "target" in path.parts:
                    continue
                try:
                    text = path.read_text(encoding="utf-8")
                except (UnicodeDecodeError, OSError):
                    continue
                if "rule:" not in text or EXAMPLES_ONLY in text:
                    continue
                for line_no, line in enumerate(text.splitlines(), 1):
                    for match in CITATION.finditer(line):
                        yield path, line_no, match.group(1)

    # -- rendering -------------------------------------------------------------

    def render_topic(self, t: Topic) -> str:
        lines = [GENERATED_HEADER.format(source=f"{t.topic}.json", topic=t.topic)]
        lines.append(f"# {t.title}\n")
        designed = [r for r in t.rules if r.status == "designed"]
        if designed:
            lines.append(
                f"*{len(designed)} of {len(t.rules)} rules below are **designed** rather than "
                "shipped, and are marked where they appear.*\n"
            )
        for r in t.rules:
            mark = "" if r.status == "shipped" else "  *(designed — not yet in the compiler)*"
            lines.append(f'<a id="{r.anchor}"></a>')
            lines.append(f"\n## {r.title}{mark}\n")
            lines.append(f"`rule:{r.id}`\n")
            body = r.body()
            if body:
                lines.append(self._linkify(body) + "\n")
            trailer = []
            if r.see_also:
                # Linked, not bare: the trailer's whole job is getting the reader to the next rule.
                trailer.append("See also " + ", ".join(
                    self._link(self.by_id[s]) if s in self.by_id else f"`rule:{s}`"
                    for s in r.see_also) + ".")
            if r.because:
                trailer.append("Decided in " + ", ".join(f"[{b}]({decision_link(b)})" for b in r.because) + ".")
            if trailer:
                lines.append("<sub>" + " ".join(trailer) + "</sub>\n")
        return "\n".join(lines).rstrip("\n") + "\n"

    def _linkify(self, body: str) -> str:
        """Turn a bare `rule:x/y` citation in prose into a link, leaving fenced code alone."""

        def sub(match: re.Match[str]) -> str:
            rid = match.group(1) or match.group(2)
            target = self.by_id.get(rid)
            if target is None:
                return match.group(0)
            if target.topic == "":
                return match.group(0)
            return self._link(target)

        out, fenced = [], False
        for line in body.splitlines():
            if line.lstrip().startswith("```"):
                fenced = not fenced
            out.append(line if fenced else LINKIFY.sub(sub, line))
        return "\n".join(out)

    @staticmethod
    def _link(rule: Rule) -> str:
        """One rule, as the markdown link every generated file points at it with."""
        return f"[`{rule.id}`]({rule.topic}.md#{rule.anchor})"

    def render_ground_rules(self) -> str:
        lines = [
            GENERATED_HEADER.format(source="docs/rules/", topic="<topic>"),
            "# The ground rules\n",
            "One line per rule, and the link to the rule that owns it. Generated from "
            "`docs/rules/` by `python tools/rules.py --render`.\n",
        ]
        for t in self.topics:
            if not t.rules:
                continue
            lines.append(f"\n## {t.title}\n")
            for r in t.rules:
                first = self._first_sentence(r.body())
                mark = "" if r.status == "shipped" else " *(designed)*"
                lines.append(f"- **{r.title}**{mark} — {first} ([`{r.id}`](rules/{t.topic}.md#{r.anchor}))")
        return "\n".join(lines).rstrip("\n") + "\n"

    def render_divergences(self) -> str:
        lines = [
            GENERATED_HEADER.format(source="docs/rules/", topic="<topic>"),
            "# Where Novis deliberately differs from PHP\n",
            "Every rule carrying a `divergesFromPhp` note, with the rule that owns it. Generated "
            "from `docs/rules/` by `python tools/rules.py --render`.\n",
            "| Topic | Divergence | Rule |",
            "|---|---|---|",
        ]
        for t in self.topics:
            for r in t.rules:
                if r.diverges:
                    lines.append(
                        f"| {t.title} | {r.diverges} | [`{r.id}`](rules/{t.topic}.md#{r.anchor}) |"
                    )
        return "\n".join(lines).rstrip("\n") + "\n"

    def generated(self) -> dict[Path, str]:
        out: dict[Path, str] = {}
        for t in self.topics:
            out[t.md_path] = self.render_topic(t)
        if self.topics:
            out[ROOT / "docs" / "ground-rules.md"] = self.render_ground_rules()
            out[ROOT / "docs" / "divergences.md"] = self.render_divergences()
        return out

    # -- helpers ---------------------------------------------------------------

    @staticmethod
    def _first_sentence(body: str) -> str:
        """The rule in one sentence, for the ground-rules index.

        The fragment's first prose paragraph is joined before a sentence is taken out of it.
        Reading one line at a time cut every hard-wrapped sentence off mid-clause and with no
        terminator -- "...and errors travel in its" -- because the period was on the next line. A
        fenced block is skipped rather than read as prose, which is what several fragments open
        with, and a citation is reduced to its bare id: the row already links to the rule.
        """
        paragraph: list[str] = []
        fenced = False
        for line in body.splitlines():
            stripped = line.strip()
            if stripped.startswith("```"):
                fenced = not fenced
                if paragraph:
                    break
                continue
            if fenced:
                continue
            if not stripped or stripped.startswith(("|", "<!--", "#", "-", ">", "*")):
                if paragraph:
                    break
                continue
            paragraph.append(stripped)
        if not paragraph:
            return "(no prose)"
        text = LINKIFY.sub(lambda m: f"`{m.group(1) or m.group(2)}`", " ".join(paragraph))
        match = re.match(r"^(.{10,220}?[.!?])(\s|$)", text)
        return match.group(1) if match else text[:219].rstrip() + "…"

    @staticmethod
    def _rel(path: Path) -> str:
        try:
            return str(path.relative_to(ROOT)).replace("\\", "/")
        except ValueError:
            return str(path)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="quiet on success, exit 1 on a finding")
    ap.add_argument("--render", action="store_true", help="write the generated markdown")
    ap.add_argument("--list", action="store_true", help="every rule id, one per line")
    ap.add_argument("--show", metavar="ID", help="one rule, metadata and body")
    ap.add_argument("--locate", metavar="ID", help="file:line for peek.py")
    ap.add_argument("--citations", action="store_true", help="every `rule:` citation, with resolution")
    ap.add_argument("--stats", action="store_true", help="one line per topic")
    args = ap.parse_args()

    # A rule's body is markdown a person wrote, so it carries whatever character the
    # prose needed -- `nonce ‖ ciphertext ‖ tag` is one -- and a console here is
    # cp1252, which has no encoding for that. Without this, `--show` prints the
    # metadata and then dies in a traceback on the body.
    try:
        sys.stdout.reconfigure(encoding="utf-8", newline="\n")
    except AttributeError:
        pass

    book = Rulebook()

    if args.list:
        for rid in sorted(book.by_id):
            print(rid)
        return 0

    if args.show:
        rule = book.by_id.get(args.show)
        if rule is None:
            print(f"no such rule: {args.show}", file=sys.stderr)
            return 1
        print(f"# {rule.title}   rule:{rule.id}")
        print(f"status:   {rule.status}")
        print(f"because:  {', '.join(rule.because) or '-'}")
        if rule.diverges:
            print(f"diverges: {rule.diverges}")
        if rule.see_also:
            print(f"seeAlso:  {', '.join(rule.see_also)}")
        print()
        print(rule.body())
        return 0

    if args.locate:
        rule = book.by_id.get(args.locate)
        if rule is None:
            print(f"no such rule: {args.locate}", file=sys.stderr)
            return 1
        print(f"{Rulebook._rel(rule.body_path)}:1")
        return 0

    if args.citations:
        for path, line_no, rid in book.iter_citations():
            state = "ok " if rid in book.by_id else "DANGLING"
            print(f"{state}  {Rulebook._rel(path)}:{line_no}  rule:{rid}")
        return 0

    if args.stats:
        if not book.topics:
            print("the rulebook does not exist yet")
            return 0
        print(f"{'topic':<20} {'rules':>5} {'shipped':>8} {'designed':>9} {'bytes':>8}")
        for t in book.topics:
            shipped = sum(1 for r in t.rules if r.status == "shipped")
            size = sum(len(r.body()) for r in t.rules)
            print(f"{t.topic:<20} {len(t.rules):>5} {shipped:>8} {len(t.rules) - shipped:>9} {size:>8}")
        total = sum(len(t.rules) for t in book.topics)
        print(f"\n{len(book.topics)} topics, {total} rules")
        return 0

    findings = book.validate() + book.check_citations()

    if args.render:
        stale: list[str] = []
        for path, text in book.generated().items():
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current == text:
                continue
            if args.check:
                stale.append(Rulebook._rel(path))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
                print(f"wrote {Rulebook._rel(path)}")
        if stale:
            print("stale generated files (run --render without --check):", file=sys.stderr)
            for s in stale:
                print(f"  {s}", file=sys.stderr)
            return 1

    if findings:
        print(f"{len(findings)} finding(s):", file=sys.stderr)
        for f in findings:
            print(str(f), file=sys.stderr)
        return 1

    if not args.check:
        if not book.topics:
            print("the rulebook does not exist yet -- migration unit B1 creates it")
        else:
            total = sum(len(t.rules) for t in book.topics)
            print(f"clean: {len(book.topics)} topics, {total} rules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
