import fs from 'node:fs'
import { defineConfig } from 'astro/config'
import starlight from '@astrojs/starlight'
import { SITE_URL, SITE_TITLE, SITE_DESCRIPTION, GITHUB_URL, DISCORD_URL, GITHUB_BRANCH } from './config/site.mjs'
import { baseLinks } from './config/base-links.mjs'

// Generated by `npm run sync` — run it after changing docs/adr or the spec.
const adrs = JSON.parse(fs.readFileSync('./src/data/adrs.json', 'utf8')) as {
  number: string
  title: string
  url: string
}[]
const core = JSON.parse(fs.readFileSync('./src/data/core.json', 'utf8')) as {
  classes: {
    id: string
    slug: string
    url: string
    members: { name: string; slug: string; url: string }[]
  }[]
}

// Custom syntax highlighting for Novis code fences (```novis / ```nvs).
const novisGrammar = JSON.parse(fs.readFileSync('./config/novis.tmLanguage.json', 'utf8'))
novisGrammar.aliases = ['novis', 'nvs']

const coreSidebar = core.classes.map((cls) => ({
  label: cls.id.replace(/\./g, '\\'),
  collapsed: true,
  items: [
    { label: 'Overview', link: cls.url },
    ...cls.members.map((m) => ({ label: m.name, link: m.url })),
  ],
}))

export default defineConfig({
  site: SITE_URL,
  // Deploying under a subfolder: set ASTRO_BASE, or pass `--base /sub/` on
  // the CLI (which overrides the env var) for a one-off build, and every
  // link and asset URL gets the prefix — sidebar/nav via Starlight, content
  // links via the baseLinks() integration below, component links via
  // src/lib/base.ts. Unset, the site builds for the webroot as before.
  base: process.env.ASTRO_BASE,
  trailingSlash: 'ignore',
  integrations: [
    baseLinks(),
    starlight({
      title: SITE_TITLE,
      description: SITE_DESCRIPTION,
      customCss: ['./src/styles/custom.css'],
      routeMiddleware: './src/routeData.ts',
      social: [
        { icon: 'github', label: 'GitHub', href: GITHUB_URL },
        { icon: 'discord', label: 'Discord', href: DISCORD_URL },
      ],
      editLink: {
        // Handwritten docs pages get an edit link; generated pages opt out
        // with `editUrl: false` in their frontmatter.
        baseUrl: `${GITHUB_URL}/edit/${GITHUB_BRANCH}/website/`,
      },
      lastUpdated: true,
      components: {
        Header: './src/components/Header.astro',
        Footer: './src/components/Footer.astro',
        Sidebar: './src/components/Sidebar.astro',
        Head: './src/components/Head.astro',
        PageTitle: './src/components/PageTitle.astro',
        MobileMenuFooter: './src/components/MobileMenuFooter.astro',
      },
      expressiveCode: {
        shiki: {
          langs: [novisGrammar],
        },
      },
      head: [
        { tag: 'meta', attrs: { name: 'theme-color', content: '#2563eb' } },
        { tag: 'meta', attrs: { property: 'og:site_name', content: SITE_TITLE } },
      ],
      sidebar: [
        {
          label: 'Getting started',
          items: [
            { label: 'What is Novis?', link: '/docs/' },
            { label: 'Installation', link: '/docs/getting-started/installation/' },
            { label: 'Hello, World!', link: '/docs/getting-started/hello-world/' },
          ],
        },
        { label: 'What Novis has decided', link: '/docs/decisions/' },
        { label: 'Release notes', link: '/docs/release-notes/' },
        {
          label: 'Core reference',
          collapsed: true,
          items: coreSidebar,
        },
        {
          label: 'ADRs',
          collapsed: true,
          items: [
            { label: 'About the ADRs', link: '/docs/adr/' },
            ...adrs.map((a) => ({ label: `${a.number} ${a.title}`, link: a.url })),
          ],
        },
      ],
    }),
  ],
})
