import fs from 'node:fs'
import { defineConfig } from 'astro/config'
import starlight from '@astrojs/starlight'
import { SITE_URL, SITE_TITLE, SITE_DESCRIPTION, GITHUB_URL, DISCORD_URL, GITHUB_BRANCH } from './config/site.mjs'
import { baseLinks } from './config/base-links.mjs'
import { externalLinks } from './config/external-links.mjs'

// Generated by `npm run sync` — run it after changing docs/adr or the spec.
const adrs = JSON.parse(fs.readFileSync('./src/data/adrs.json', 'utf8')) as {
  number: string
  title: string
  url: string
}[]
const core = JSON.parse(fs.readFileSync('./src/data/core.json', 'utf8')) as {
  classes: {
    id: string
    slug: string
    url: string
    members: { name: string; slug: string; url: string }[]
  }[]
}

// Custom syntax highlighting for Novis code fences (```novis / ```nvs).
const novisGrammar = JSON.parse(fs.readFileSync('./config/novis.tmLanguage.json', 'utf8'))
novisGrammar.aliases = ['novis', 'nvs']

const coreSidebar = core.classes.map((cls) => ({
  label: cls.id.replace(/\./g, '\\'),
  collapsed: true,
  items: [
    { label: 'Overview', link: cls.url },
    ...cls.members.map((m) => ({ label: m.name, link: m.url })),
  ],
}))

export default defineConfig({
  site: SITE_URL,
  // Deploying under a subfolder: set ASTRO_BASE, or pass `--base /sub/` on
  // the CLI (which overrides the env var) for a one-off build, and every
  // link and asset URL gets the prefix — sidebar/nav via Starlight, content
  // links via the baseLinks() integration below, component links via
  // src/lib/base.ts. Unset, the site builds for the webroot as before.
  base: process.env.ASTRO_BASE,
  trailingSlash: 'ignore',
  integrations: [
    baseLinks(),
    externalLinks(),
    starlight({
      title: SITE_TITLE,
      description: SITE_DESCRIPTION,
      // The mark in the header, standing in for the wordmark: the site nav's
      // first link already reads "Novis" beside it, so the mark alone carries
      // the title, and its alt text keeps it for screen readers. One source
      // of truth: media/novis-logo.png is the design export, sized down by
      // CSS in src/components/Header.astro. public/favicon.ico and
      // public/apple-touch-icon.png are cut from the same file — see the
      // website README's "Logo and favicon" section for the command.
      logo: { src: './media/novis-logo.png', alt: SITE_TITLE, replacesTitle: true },
      favicon: '/favicon.ico',
      customCss: ['./src/styles/custom.css'],
      routeMiddleware: './src/routeData.ts',
      social: [
        { icon: 'github', label: 'GitHub', href: GITHUB_URL },
        { icon: 'discord', label: 'Discord', href: DISCORD_URL },
      ],
      editLink: {
        // Handwritten docs pages get an edit link; generated pages opt out
        // with `editUrl: false` in their frontmatter.
        baseUrl: `${GITHUB_URL}/edit/${GITHUB_BRANCH}/website/`,
      },
      lastUpdated: true,
      components: {
        Header: './src/components/Header.astro',
        Footer: './src/components/Footer.astro',
        Sidebar: './src/components/Sidebar.astro',
        Head: './src/components/Head.astro',
        PageTitle: './src/components/PageTitle.astro',
        MobileMenuFooter: './src/components/MobileMenuFooter.astro',
        // The mobile menu button on every page, sidebar or not.
        PageFrame: './src/components/PageFrame.astro',
        // The two Starlight components that link off the site, with the
        // external-link rule applied — see config/external-links.mjs.
        SocialIcons: './src/components/SocialIcons.astro',
        EditLink: './src/components/EditLink.astro',
      },
      expressiveCode: {
        shiki: {
          langs: [novisGrammar],
        },
        styleOverrides: {
          // A code block's frame already follows the site's colors (Starlight
          // hands Expressive Code its UI tokens), but the code surface itself
          // comes from the syntax theme — a cold grey under a warm page. The
          // value is --nv-code-bg in src/styles/custom.css, with the rest of
          // the palette.
          codeBackground: 'var(--nv-code-bg)',
        },
      },
      head: [
        // The palette's accent, as it appears in the light theme — the browser
        // chrome sits above a light page. Kept in step with --nv-accent in
        // src/styles/custom.css, which is where the palette lives.
        { tag: 'meta', attrs: { name: 'theme-color', content: '#b20038' } },
        { tag: 'meta', attrs: { property: 'og:site_name', content: SITE_TITLE } },
      ],
      sidebar: [
        {
          label: 'Getting started',
          items: [
            { label: 'What is Novis?', link: '/docs/' },
            { label: 'Installation', link: '/docs/getting-started/installation/' },
            { label: 'Hello, World!', link: '/docs/getting-started/hello-world/' },
          ],
        },
        { label: 'What Novis has decided', link: '/docs/decisions/' },
        { label: 'Release notes', link: '/docs/release-notes/' },
        {
          label: 'Core reference',
          collapsed: true,
          items: coreSidebar,
        },
        {
          label: 'ADRs',
          collapsed: true,
          items: [
            { label: 'About the ADRs', link: '/docs/adr/' },
            ...adrs.map((a) => ({ label: `${a.number} ${a.title}`, link: a.url })),
          ],
        },
      ],
    }),
  ],
})
