import fs from 'node:fs'
import { defineConfig } from 'astro/config'
import starlight from '@astrojs/starlight'
import { SITE_URL, SITE_TITLE, SITE_DESCRIPTION, GITHUB_URL, DISCORD_URL, GITHUB_BRANCH, INSTALL } from './config/site.mjs'
import { baseLinks } from './config/base-links.mjs'
import { externalLinks } from './config/external-links.mjs'

// Generated by `npm run sync` — run it after changing the spec.
const core = JSON.parse(fs.readFileSync('./src/data/core.json', 'utf8')) as {
  classes: {
    id: string
    slug: string
    url: string
    members: { name: string; slug: string; url: string }[]
  }[]
}

// Configuration and CLI pages, from src/data/reference.json, one sidebar
// group per page group in the order the data lists them.
const reference = JSON.parse(fs.readFileSync('./src/data/reference.json', 'utf8')) as {
  pages: { area: 'config' | 'cli'; url: string; title: string; group: string }[]
}
const referenceSidebar = (area: 'config' | 'cli') => {
  const groups = new Map<string, { label: string; link: string }[]>()
  for (const p of reference.pages.filter((p) => p.area === area)) {
    if (!groups.has(p.group)) groups.set(p.group, [])
    groups.get(p.group)!.push({ label: p.title.replace(/`/g, ''), link: p.url })
  }
  return [...groups].map(([label, items]) => ({ label, collapsed: true, items }))
}

// Syntax highlighting for Novis code fences (```novis / ```nvs). `npm run sync:render` writes this
// file from the editors' grammar.
const novisGrammar = JSON.parse(fs.readFileSync('./config/novis.tmLanguage.json', 'utf8'))

const coreSidebar = core.classes.map((cls) => ({
  label: cls.id.replace(/\./g, '\\'),
  collapsed: true,
  items: [
    { label: 'Overview', link: cls.url },
    ...cls.members.map((m) => ({ label: m.name, link: m.url })),
  ],
}))

export default defineConfig({
  site: SITE_URL,
  // Deploying under a subfolder: set ASTRO_BASE, or pass `--base /sub/` on
  // the CLI (which overrides the env var) for a one-off build, and every
  // link and asset URL gets the prefix — sidebar/nav via Starlight, content
  // links via the baseLinks() integration below, component links via
  // src/lib/base.ts. Unset, the site builds for the webroot as before.
  base: process.env.ASTRO_BASE,
  trailingSlash: 'ignore',
  integrations: [
    baseLinks(),
    externalLinks(),
    starlight({
      title: SITE_TITLE,
      description: SITE_DESCRIPTION,
      // The mark in the header replaces the wordmark and links to the home
      // page. Its alt text keeps the title for screen readers. One source
      // of truth: media/novis-logo.png is the design export, sized down by
      // CSS in src/components/Header.astro. public/favicon.ico and
      // public/apple-touch-icon.png are cut from the same file — see the
      // website README's "Logo and favicon" section for the command.
      logo: { src: './media/novis-logo.png', alt: SITE_TITLE, replacesTitle: true },
      favicon: '/favicon.ico',
      customCss: ['./src/styles/custom.css'],
      routeMiddleware: './src/routeData.ts',
      social: [
        { icon: 'github', label: 'GitHub', href: GITHUB_URL },
        { icon: 'discord', label: 'Discord', href: DISCORD_URL },
      ],
      editLink: {
        // Handwritten docs pages get an edit link; generated pages opt out
        // with `editUrl: false` in their frontmatter.
        baseUrl: `${GITHUB_URL}/edit/${GITHUB_BRANCH}/website/`,
      },
      // No "Last updated" stamp: it is the git commit date, and a page that is still correct
      // reads as stale the moment something near it is edited. `git log` is the changelog.
      lastUpdated: false,
      components: {
        Header: './src/components/Header.astro',
        Footer: './src/components/Footer.astro',
        Sidebar: './src/components/Sidebar.astro',
        Head: './src/components/Head.astro',

        MobileMenuFooter: './src/components/MobileMenuFooter.astro',
        // The mobile menu button on every page, sidebar or not.
        PageFrame: './src/components/PageFrame.astro',
        // The two Starlight components that link off the site, with the
        // external-link rule applied — see config/external-links.mjs.
        SocialIcons: './src/components/SocialIcons.astro',
        EditLink: './src/components/EditLink.astro',
      },
      expressiveCode: {
        shiki: {
          langs: [novisGrammar],
        },
        styleOverrides: {
          // A code block's frame already follows the site's colors (Starlight
          // hands Expressive Code its UI tokens), but the code surface itself
          // comes from the syntax theme — a cold grey under a warm page. The
          // value is --nv-code-bg in src/styles/custom.css, with the rest of
          // the palette.
          codeBackground: 'var(--nv-code-bg)',
        },
      },
      head: [
        // The palette's accent, as it appears in the light theme — the browser
        // chrome sits above a light page. Kept in step with --nv-accent in
        // src/styles/custom.css, which is where the palette lives.
        { tag: 'meta', attrs: { name: 'theme-color', content: '#b20038' } },
        { tag: 'meta', attrs: { property: 'og:site_name', content: SITE_TITLE } },
      ],
      // One top-level group per area, labelled as AREAS and INSTALL in
      // config/site.mjs. A page shows only the group of the area its URL is
      // in: src/routeData.ts picks it, and a page outside every area has no
      // sidebar.
      sidebar: [
        {
          label: 'Guides',
          items: [
            { label: 'Overview', link: '/guides/' },
            {
              label: 'Why people pick Novis',
              items: [
                { label: 'Overview', link: '/guides/why-novis/' },
                { label: 'HTML that escapes itself', link: '/guides/why-novis/html-escapes/' },
                { label: 'Input from outside is tainted', link: '/guides/why-novis/tainted-input/' },
                { label: 'Secrets are never printed', link: '/guides/why-novis/secret-values/' },
                { label: 'One failure stops one program', link: '/guides/why-novis/one-failure/' },
                { label: 'No surprises from null', link: '/guides/why-novis/no-null-surprises/' },
                { label: 'Every conversion is checked', link: '/guides/why-novis/checked-conversions/' },
                { label: 'JSON with types', link: '/guides/why-novis/typed-json/' },
                { label: 'Text is Unicode', link: '/guides/why-novis/unicode-strings/' },
                { label: 'Tests are part of the language', link: '/guides/why-novis/tests-in-code/' },
                { label: 'Errors with a default in one line', link: '/guides/why-novis/simple-errors/' },
                { label: 'One standard library', link: '/guides/why-novis/one-library/' },
              ],
            },
            {
              label: 'A Tour of Novis',
              items: [
                { label: 'Start the Tour', link: '/guides/tour/' },
                { label: '1. Methods and types', link: '/guides/tour/01-methods-and-types/' },
                { label: '2. Arrays and loops', link: '/guides/tour/02-arrays-and-loops/' },
                { label: '3. Classes and objects', link: '/guides/tour/03-classes-and-objects/' },
                { label: '4. Values that may be missing', link: '/guides/tour/04-null/' },
                { label: '5. Errors', link: '/guides/tour/05-errors/' },
                { label: '6. Enums and match', link: '/guides/tour/06-enums-and-match/' },
                { label: '7. JSON', link: '/guides/tour/07-json/' },
                { label: '8. Tests', link: '/guides/tour/08-tests/' },
                { label: '9. HTML', link: '/guides/tour/09-html/' },
                { label: '10. A web application', link: '/guides/tour/10-web-app/' },
              ],
            },
            {
              label: 'Simple programs',
              items: [
                { label: 'Overview', link: '/guides/simple-programs/' },
                { label: 'A CSV report', link: '/guides/simple-programs/csv-report/' },
                { label: 'A JSON API', link: '/guides/simple-programs/json-api/' },
                { label: 'A file watcher', link: '/guides/simple-programs/file-watcher/' },
                { label: 'A web scraper', link: '/guides/simple-programs/scraper/' },
                { label: 'A form handler', link: '/guides/simple-programs/form-handler/' },
                { label: 'A scheduled job', link: '/guides/simple-programs/scheduled-job/' },
              ],
            },
            {
              label: 'How to use Novis',
              items: [
                { label: 'Overview', link: '/guides/how-to-use/' },
                { label: 'Project layout', link: '/guides/how-to-use/project-layout/' },
                { label: 'Configuration', link: '/guides/how-to-use/configuration/' },
                { label: 'Handling requests', link: '/guides/how-to-use/requests/' },
                { label: 'Errors', link: '/guides/how-to-use/errors/' },
                { label: 'Tainted input', link: '/guides/how-to-use/tainted-input/' },
                { label: 'Limits', link: '/guides/how-to-use/limits/' },
              ],
            },
            {
              label: 'Cookbook',
              items: [
                { label: 'Overview', link: '/guides/cookbook/' },
                { label: 'Read a JSON body', link: '/guides/cookbook/read-json-body/' },
                { label: 'Validate a form', link: '/guides/cookbook/validate-form/' },
                { label: 'Page through database rows', link: '/guides/cookbook/page-db-rows/' },
                { label: 'Save an uploaded file', link: '/guides/cookbook/upload-file/' },
                { label: 'Call an HTTP API', link: '/guides/cookbook/call-http-api/' },
                { label: 'Send a signed link', link: '/guides/cookbook/signed-url/' },
                { label: 'Store a password', link: '/guides/cookbook/hash-password/' },
                { label: 'Keep a value in a cookie', link: '/guides/cookbook/signed-cookie/' },
                { label: 'Cache a slow result', link: '/guides/cookbook/cache-value/' },
                { label: 'Schedule a job', link: '/guides/cookbook/schedule-job/' },
              ],
            },
            {
              label: 'Testing your app',
              items: [
                { label: 'Overview', link: '/guides/testing/' },
                { label: 'Running tests', link: '/guides/testing/run-tests/' },
                { label: 'Test doubles', link: '/guides/testing/test-doubles/' },
                { label: 'Testing a page', link: '/guides/testing/test-a-route/' },
                { label: 'Coverage reports', link: '/guides/testing/coverage/' },
              ],
            },
            {
              label: 'Going to production',
              items: [
                { label: 'Overview', link: '/guides/production/' },
                { label: 'Run as a service', link: '/guides/production/run-as-a-service/' },
                { label: 'Docker', link: '/guides/production/docker/' },
                { label: 'Behind a reverse proxy', link: '/guides/production/reverse-proxy/' },
                { label: 'Limits and logs', link: '/guides/production/limits-and-logs/' },
                { label: 'Security checklist', link: '/guides/production/security-checklist/' },
              ],
            },
            {
              label: 'Example apps',
              items: [
                { label: 'Overview', link: '/guides/example-apps/' },
                { label: 'Notes', link: '/guides/example-apps/notes/' },
              ],
            },
          ],
        },
        {
          label: 'Syntax',
          items: [
            { label: 'Overview', link: '/syntax/' },
            { label: 'Start here', link: '/syntax/start-here/' },
            {
              label: 'Basics',
              items: [
                { label: 'Files and statements', link: '/syntax/basics/files-and-statements/' },
                { label: 'Comments and doc comments', link: '/syntax/basics/comments/' },
                { label: 'Variables and var', link: '/syntax/basics/variables/' },
                { label: 'Constants', link: '/syntax/basics/constants/' },
              ],
            },
            {
              label: 'Values and types',
              items: [
                { label: 'Numbers', link: '/syntax/values/numbers/' },
                { label: 'Strings and interpolation', link: '/syntax/values/strings/' },
                { label: 'Bool and null', link: '/syntax/values/bool-and-null/' },
                { label: 'Arrays and array<T>', link: '/syntax/values/arrays/' },
                { label: 'Nullable types', link: '/syntax/values/nullable/' },
                { label: 'Union types', link: '/syntax/values/union-types/' },
                { label: 'Enums', link: '/syntax/values/enums/' },
                { label: 'Converting with as', link: '/syntax/values/as/' },
                { label: 'Type tests with is', link: '/syntax/values/is/' },
                { label: 'Tainted and secret strings', link: '/syntax/values/tainted-and-secret/' },
              ],
            },
            {
              label: 'Operators',
              items: [
                { label: 'Arithmetic and assignment', link: '/syntax/operators/arithmetic/' },
                { label: 'Comparison and logic', link: '/syntax/operators/comparison/' },
                { label: '?? and ??=', link: '/syntax/operators/null-coalescing/' },
                { label: 'String operators', link: '/syntax/operators/string-operators/' },
                { label: 'The pipeline operator |>', link: '/syntax/operators/pipeline/' },
                { label: 'Precedence', link: '/syntax/operators/precedence/' },
              ],
            },
            {
              label: 'Control flow',
              items: [
                { label: 'if and else', link: '/syntax/control-flow/if/' },
                { label: 'match', link: '/syntax/control-flow/match/' },
                { label: 'switch', link: '/syntax/control-flow/switch/' },
                { label: 'while and for', link: '/syntax/control-flow/loops/' },
                { label: 'foreach', link: '/syntax/control-flow/foreach/' },
                { label: 'Iterators and generators', link: '/syntax/control-flow/iterators/' },
                { label: 'break, continue and return', link: '/syntax/control-flow/break-continue-return/' },
                { label: 'echo, unset and exit', link: '/syntax/control-flow/other-statements/' },
              ],
            },
            {
              label: 'Errors',
              items: [
                { label: 'throw, try and catch', link: '/syntax/errors/throw-and-catch/' },
                { label: 'catch as an expression', link: '/syntax/errors/catch-expression/' },
                { label: 'Error types', link: '/syntax/errors/error-types/' },
                { label: 'Rethrowing and uncaught errors', link: '/syntax/errors/rethrowing/' },
                { label: 'Limits and permissions', link: '/syntax/errors/limits/' },
                { label: 'Assertions and dumping values', link: '/syntax/errors/assert-and-dump/' },
              ],
            },
            {
              label: 'Functions',
              items: [
                { label: 'Declaring a function', link: '/syntax/functions/declaring/' },
                { label: 'Parameters and inout', link: '/syntax/functions/parameters/' },
                { label: 'Calling a function', link: '/syntax/functions/calls/' },
                { label: 'Closures with fn', link: '/syntax/functions/closures/' },
              ],
            },
            {
              label: 'Classes and objects',
              items: [
                { label: 'Declaring a class', link: '/syntax/classes/declaring/' },
                { label: 'Properties and constants', link: '/syntax/classes/properties/' },
                { label: 'Methods and inheritance', link: '/syntax/classes/methods-and-inheritance/' },
                { label: 'Interfaces', link: '/syntax/classes/interfaces/' },
                { label: 'Stringable, Comparable and Parses', link: '/syntax/classes/standard-interfaces/' },
                { label: 'Property hooks', link: '/syntax/classes/property-hooks/' },
                { label: 'Working with objects', link: '/syntax/classes/objects/' },
                { label: 'Object literals and shapes', link: '/syntax/classes/object-literals/' },
              ],
            },
            {
              label: 'Programs and files',
              items: [
                { label: 'Namespaces, use and autoload', link: '/syntax/programs/namespaces/' },
                { label: 'Running another file with require', link: '/syntax/programs/require/' },
                { label: 'File paths and ending a program', link: '/syntax/programs/file-paths-and-exit/' },
              ],
            },
            {
              label: 'Concurrency',
              items: [
                { label: 'Running tasks at the same time', link: '/syntax/concurrency/tasks/' },
                { label: 'Limits, deadlines and errors', link: '/syntax/concurrency/limits-and-errors/' },
                { label: 'Channels', link: '/syntax/concurrency/channels/' },
                { label: 'Running a separate program', link: '/syntax/concurrency/isolates/' },
              ],
            },
            {
              label: 'Attributes',
              items: [
                { label: 'Writing and reading attributes', link: '/syntax/attributes/writing-and-reading/' },
                { label: 'Objects as JSON', link: '/syntax/attributes/json/' },
                { label: 'Routes and access', link: '/syntax/attributes/routes/' },
                { label: 'Commands and finding classes', link: '/syntax/attributes/commands-and-discovery/' },
              ],
            },
            {
              label: 'Testing',
              items: [
                { label: 'Writing and running tests', link: '/syntax/testing/writing-tests/' },
                { label: 'Fixtures, data rows and assertions', link: '/syntax/testing/fixtures-and-assertions/' },
              ],
            },
          ],
        },
        {
          label: 'Reference',
          items: [
            { label: 'Overview', link: '/reference/' },
            {
              label: 'Core classes',
              items: [{ label: 'All classes', link: '/reference/core/' }, ...coreSidebar],
            },
            {
              label: 'Configuration',
              items: [{ label: 'All blocks', link: '/reference/config/' }, ...referenceSidebar('config')],
            },
            {
              label: 'CLI commands',
              items: [{ label: 'All commands', link: '/reference/cli/' }, ...referenceSidebar('cli')],
            },
          ],
        },
        {
          label: 'In-Depth',
          items: [
            { label: 'Overview', link: '/in-depth/' },
            { label: 'What Novis is for', link: '/in-depth/what-for/' },
            { label: 'What Novis will never be', link: '/in-depth/never/' },
            { label: 'How we decide', link: '/in-depth/how-we-decide/' },
            { label: 'Design principles', link: '/in-depth/design-principles/' },
            {
              label: 'Concepts',
              items: [
                { label: 'Overview', link: '/in-depth/concepts/' },
                { label: 'One request cannot hurt another', link: '/in-depth/concepts/isolation/' },
                { label: 'Tainted input', link: '/in-depth/concepts/tainted-input/' },
                { label: 'Memory and CPU limits', link: '/in-depth/concepts/limits/' },
                { label: 'Compiled, never interpreted', link: '/in-depth/concepts/compiled/' },
                { label: 'Strings are UTF-8', link: '/in-depth/concepts/utf8-strings/' },
              ],
            },
            { label: 'Where Novis falls behind', link: '/in-depth/falls-behind/' },
            { label: 'Roadmap', link: '/in-depth/roadmap/' },
            { label: 'What changed', link: '/in-depth/what-changed/' },
          ],
        },
        {
          label: INSTALL.label,
          items: [
            { label: 'Install Novis', link: INSTALL.href },
            { label: 'Hello, World!', link: '/install/hello-world/' },
            { label: 'The editor extension', link: '/install/editor/' },
            { label: 'Install on a server', link: '/install/server/' },
          ],
        },
      ],
    }),
  ],
})
