//! Every PHP built-in name, and what an editor may offer in its place.
//!
//! `rule:php-migration/every-php-builtin-is-a-completion-candidate` makes every
//! name in the differential oracle's own inventory a completion candidate from
//! the day the layer ships, and the migration table's row for that name what
//! the item *says*. The two files are two jobs and neither is copied into the
//! other, so coverage of the table never decides whether the feature works,
//! only how good one answer is: a name with no row is an item that says
//! *undecided*, which reads as *Novis has audited this and owes you an answer*,
//! where a name that does not appear at all reads as *Novis cannot do this*.
//!
//! [`CANDIDATES`] is that join, generated by `build.rs` — which is where the
//! two documents are read, and whose own module doc owns what it may fail the
//! build on. This module is the third input: the registry, which decides which
//! of the four shapes below a row's destination gets, and which a build script
//! cannot reach because it cannot link the crate it builds.
//!
//! # Four shapes, and three of them insert nothing
//!
//! [`Item`] is `rule:ide/three-of-four-item-shapes-insert-nothing`'s table as
//! an enum, and [`Item::insertion`] is the whole of what an editor may type on
//! a developer's behalf. **"Inserts nothing" is the absence of an edit, not an
//! empty string**, which is why that method returns an `Option` rather than a
//! `&str` — an empty insertion is an edit that replaces the typed prefix with
//! nothing, and the three shapes that insert nothing must leave the buffer
//! alone.
//!
//! A registered destination is the one shape that inserts, and it inserts the
//! **Novis** spelling: the PHP name never reaches a file, because a PHP name
//! that resolved at run time would be the second name
//! `rule:statements/nothing-gets-a-second-name` removes. An editor that
//! inserted a call which then failed to resolve would be worse than one that
//! offered nothing — the developer could not tell the suggestion's mistake from
//! their own — which is the whole of
//! `rule:php-migration/an-item-inserts-only-a-registered-member`.
//!
//! # A destination resolves exactly, and a namespace does not answer for it
//!
//! [`Destination::is_registered`] asks [`registry::class`] for the class the
//! cell spells and nothing else. `tests/spec_registry_coverage.rs` widens an
//! unregistered nested name to its own namespace, because it is a *coverage*
//! gate and `Core\Db\Queryable`'s members are registered on the two classes
//! that implement it; here that widening would have the editor insert a
//! spelling the table does not name, chosen from among the implementors, so a
//! destination naming an interface appears and inserts nothing instead. That is
//! the safe direction, and it stops being the answer the day the interface
//! carries a registry row of its own.

use crate::registry::{self, CoreMethod};

/// Which half of the oracle inventory a name comes from.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Kind {
    /// An internal function — the inventory's `[functions]` section.
    Function,
    /// An internal type — the inventory's `[types]` section.
    Type,
}

/// The migration table's verdict on one PHP name.
///
/// The four `docs/spec/02-php-migration.md` § *How to read a row* writes, and
/// nothing else: a name with no row at all carries [`Self::Open`], which is
/// what that file means by "absence of a row means the same thing".
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Outcome {
    /// A `Core` member does this job, and the cell names it.
    Member,
    /// An operator or keyword does this job; no member exists, by
    /// `rule:core-api/shape-rules` R17.
    Language,
    /// Nothing does this job. The cell says why, and gives the rewrite where
    /// one exists.
    Dropped,
    /// Not yet decided — or no row, which means the same thing.
    Open,
}

/// A `Core\X::member` spelling a row's Novis cell names.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Destination {
    /// The fully-qualified class, backslash-separated as source writes it.
    pub class: &'static str,
    /// The member on it.
    pub member: &'static str,
}

impl Destination {
    /// The spelling a Novis program writes, which is what an item may insert.
    #[must_use]
    pub fn spelling(&self) -> String {
        format!("{}::{}", self.class, self.member)
    }

    /// The registry row behind this destination, or `None` when the registry
    /// holds no such member.
    ///
    /// This is the signature an item renders as its detail, per ADR 0088 § 5.
    /// A destination naming a class **constant** resolves through
    /// [`Self::is_registered`] and has no row here, a constant having a value
    /// and no signature.
    #[must_use]
    pub fn method(&self) -> Option<&'static CoreMethod> {
        registry::class(self.class)?
            .members()
            .find(|member| member.name == self.member)
    }

    /// Whether the registry holds this destination, as a member or as a class
    /// constant.
    #[must_use]
    pub fn is_registered(&self) -> bool {
        registry::class(self.class).is_some_and(|class| {
            class.members().any(|member| member.name == self.member)
                || class.constant(self.member).is_some()
        })
    }
}

/// What one completion item for a PHP name may do.
///
/// `rule:ide/three-of-four-item-shapes-insert-nothing`'s four rows, in its own
/// order. Only the first carries an insertion.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Item {
    /// A `member` or `language` row whose destination the registry holds: the
    /// item inserts it, with the signature [`Destination::method`] carries.
    Inserts(Destination),
    /// A `member` or `language` row whose destination the registry does not
    /// hold. It appears, names what it is waiting on, and inserts nothing.
    ///
    /// `None` is the same shape reached the other way: a cell that names no
    /// `Core\X::member` spelling at all, which is every `language` row where an
    /// operator does the job, and every `member` row pointing at an instance
    /// member of a value (`$file->close`) rather than at a static spelling.
    /// Both insert nothing for one reason — there is nothing here the compiler
    /// resolves.
    NotRegistered(Option<Destination>),
    /// A `dropped` row. It appears with the row's reason and rewrite, and
    /// inserts nothing.
    Dropped,
    /// An `open` row, or no row at all. It appears, says it is undecided, and
    /// inserts nothing.
    Undecided,
}

impl Item {
    /// The text an editor may type on the developer's behalf — `None` for the
    /// three shapes that insert nothing.
    ///
    /// An `Option` and not an empty string: an empty insertion is still an
    /// edit, and it replaces whatever prefix the developer had typed.
    #[must_use]
    pub fn insertion(&self) -> Option<String> {
        match self {
            Self::Inserts(destination) => Some(destination.spelling()),
            Self::NotRegistered(_) | Self::Dropped | Self::Undecided => None,
        }
    }
}

/// One PHP name the oracle inventory lists, with the migration table's row for
/// it.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Candidate {
    /// The built-in, exactly as PHP spells it.
    pub php: &'static str,
    /// Which section of the inventory listed it.
    pub kind: Kind,
    /// The migration table's outcome for it.
    pub outcome: Outcome,
    /// The row's Novis cell, verbatim and as markdown — the reason and the
    /// rewrite a `dropped` item shows, and the prose a `member` row carries
    /// beside its spelling. Empty for a name with no row.
    pub cell: &'static str,
    /// Every `Core\X::member` spelling the cell names, in the order it writes
    /// them.
    pub destinations: &'static [Destination],
}

impl Candidate {
    /// The items this candidate offers: one per destination, or one for the
    /// whole row where it names none.
    ///
    /// A cell naming more than one destination is prose the converter may not
    /// guess at, and is a genuine ambiguity there. It is not one here —
    /// completion has a person in the loop, so the row becomes one item per
    /// destination and the developer picks. This is the single place the editor
    /// may offer more than the converter, and it follows from the human rather
    /// than from a better table.
    #[must_use]
    pub fn items(&self) -> Vec<Item> {
        match self.outcome {
            Outcome::Member | Outcome::Language => {
                if self.destinations.is_empty() {
                    return vec![Item::NotRegistered(None)];
                }
                self.destinations
                    .iter()
                    .map(|destination| {
                        if destination.is_registered() {
                            Item::Inserts(*destination)
                        } else {
                            Item::NotRegistered(Some(*destination))
                        }
                    })
                    .collect()
            }
            Outcome::Dropped => vec![Item::Dropped],
            Outcome::Open => vec![Item::Undecided],
        }
    }
}

/// Every candidate whose PHP spelling starts with `prefix`.
///
/// [`CANDIDATES`] is sorted by that spelling, so this is the one contiguous run
/// of it that matches — what a completion arm wants, and the reason the table
/// is sorted rather than left in the inventory's section order.
#[must_use]
pub fn starting_with(prefix: &str) -> &'static [Candidate] {
    let start = CANDIDATES.partition_point(|candidate| candidate.php < prefix);
    let rest = &CANDIDATES[start..];
    let end = rest.partition_point(|candidate| candidate.php.starts_with(prefix));
    &rest[..end]
}

/// The candidate for the PHP function a program called as `name`.
///
/// Matched the way PHP resolves a call: without regard to ASCII case, and with
/// the one leading `\` a fully-qualified call writes. A name under a namespace
/// is nobody's built-in function and has no candidate.
#[must_use]
pub fn function(name: &str) -> Option<&'static Candidate> {
    let name = name.strip_prefix('\\').unwrap_or(name).to_ascii_lowercase();
    starting_with(&name)
        .iter()
        .find(|candidate| candidate.php == name && candidate.kind == Kind::Function)
}

/// What a diagnostic says became of the PHP function a program called as
/// `name`: the clause that finishes the sentence "PHP's `name` …".
///
/// This is `nvs_hir::PhpFunctions`' lookup, which is how `E0320`'s help names
/// the spelling the language wants for the name that was written.
///
/// A `member` or `language` row answers with the code span its cell opens on,
/// which is the spelling the row is about. The cell's prose is not repeated: a
/// row is written to be read under the row above it, and a cell that opens on
/// prose ("the same pair") names no spelling a reader could use on its own, so
/// such a row answers `None` and the diagnostic keeps its general help. So does
/// a row naming a destination the registry does not hold, for
/// `rule:php-migration/an-item-inserts-only-a-registered-member`'s reason: a
/// suggestion that does not resolve is worse than none.
///
/// A `dropped` row answers that nothing does the job, and leaves the reason
/// and the rewrite to the table.
#[must_use]
pub fn became(name: &str) -> Option<String> {
    let candidate = function(name)?;
    match candidate.outcome {
        Outcome::Member | Outcome::Language => {
            let (written, _) = candidate
                .cell
                .trim_start()
                .strip_prefix('`')?
                .split_once('`')?;
            candidate
                .destinations
                .iter()
                .all(Destination::is_registered)
                .then(|| format!("is `{written}` here"))
        }
        Outcome::Dropped => Some("has no counterpart here".to_owned()),
        Outcome::Open => None,
    }
}

include!(concat!(env!("OUT_DIR"), "/php-names.rs"));
